In [1]:
from scripts.python.simulateCommunityModel import simulateCommunityModel
from scripts.python.simulateCommunityModel_with_beta import simulateCommunityModel_with_beta
import pandas as pd

In [2]:
mu = 1.786 # growth rate
modelNames = ['Lachnospiraceae_species','Bacteroides_ovatus','Bifidobacterium_longum',
'Collinsella_aerofaciens','Escherichia_coli','Klebsiella_aerogenes','Muricomes_intestini','Parabacteroides_distasonis']
modelPaths = ['./Data/HDC/HDC1_gapseq/HDC_180_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_376_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_370_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_374_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_382_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_bin1.xml',
'./Data/HDC/HDC1_gapseq/HDC_380_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_378_genome.xml']
modelWeights = [0.000001,0.008976,0.000124,0.000007,0.000085,0.000121,0.000082,0.000426]

modelDetails = pd.DataFrame({'Name':modelNames,'Path':modelPaths,'weight':modelWeights})
modelDetails.head()

,Name,Path,weight
0,Lachnospiraceae_species,./Data/HDC/HDC1_gapseq/HDC_180_genome.xml,0.000001
1,Bacteroides_ovatus,./Data/HDC/HDC1_gapseq/HDC_376_genome.xml,0.008976
2,Bifidobacterium_longum,./Data/HDC/HDC1_gapseq/HDC_370_genome.xml,0.000124
3,Collinsella_aerofaciens,./Data/HDC/HDC1_gapseq/HDC_374_genome.xml,0.000007
4,Escherichia_coli,./Data/HDC/HDC1_gapseq/HDC_382_genome.xml,0.000085

In [3]:
# exchange reactions (from metabolomics data)
exchangeRate = pd.read_excel('./Data/HDC/HDC1_metabolomics_preliminary_formodelling2.xlsx')
exchangeRate['GF_conc'] = exchangeRate['GF_Mean (mmol per g)']
exchangeRate['Microbiome_conc'] = exchangeRate['HDC1_Mean (mmol per g)']
exchangeRate['GF_conc_sd'] = exchangeRate['GF_Standard deviation (mmol per g)']
exchangeRate['Microbiome_conc_sd'] = exchangeRate['HDC1_Standard deviation (mmol per g)']
exchangeRate['metabolite ID'] = exchangeRate['modelseed ID']
exchangeRate.head()

,Quantified compounds,modelseed ID,HMDB ID,Metabolite present in gapseq model exchange reactions?,GF_Mean (mmol per g),GF_Standard deviation (mmol per g),HDC1_Mean (mmol per g),HDC1_Standard deviation (mmol per g),Consumed or produced?,GF_conc,Microbiome_conc,GF_conc_sd,Microbiome_conc_sd,metabolite ID
0,Guanosine,cpd00311,HMDB0000133,Y,0.000523,0.000386,0.000284,0.000330,consumed,0.000523,0.000284,0.000386,0.000330,cpd00311
1,Argnine,cpd00051,HMDB0000517,Y,0.007678,0.006080,0.002062,0.001895,consumed,0.007678,0.002062,0.006080,0.001895,cpd00051
2,Asparagine,cpd00132,HMDB0000168,Y,0.007764,0.005528,0.000069,0.000080,consumed,0.007764,0.000069,0.005528,0.000080,cpd00132
3,Glutamine,cpd00053,HMDB0000641,Y,0.008064,0.005168,0.002055,0.001684,consumed,0.008064,0.002055,0.005168,0.001684,cpd00053
4,Glycine,cpd00033,HMDB0000123,Y,0.015165,0.011155,0.008150,0.006380,consumed,0.015165,0.008150,0.011155,0.006380,cpd00033

In [4]:
# loading the production rates
productionRate = pd.read_excel('./Data/HDC/HDC1_metabolomics_preliminary_formodelling2.xlsx',sheet_name='produced')
productionRate['GF_conc'] = productionRate['GF_Mean (mmol per g)']
productionRate['Microbiome_conc'] = productionRate['HDC1_Mean (mmol per g)']
productionRate['GF_conc_sd'] = productionRate['GF_Standard deviation (mmol per g)']
productionRate['Microbiome_conc_sd'] = productionRate['HDC1_Standard deviation (mmol per g)']
productionRate['metabolite ID'] = productionRate['modelseed ID']
productionRate.head()

,Quantified compounds,modelseed ID,HMDB ID,Metabolite present in gapseq model exchange reactions?,GF_Mean (mmol per g),GF_Standard deviation (mmol per g),HDC1_Mean (mmol per g),HDC1_Standard deviation (mmol per g),Consumed or produced?,GF_conc,Microbiome_conc,GF_conc_sd,Microbiome_conc_sd,metabolite ID
0,Adenosine,cpd00182,HMDB0000050,Y,1.410623e-05,0.000017,5.068257e-05,0.000053,produced,1.410623e-05,5.068257e-05,0.000017,0.000053,cpd00182
1,Cytidine,cpd00367,HMDB0000089,Y,3.014813e-04,0.000256,4.632410e-04,0.000503,produced,3.014813e-04,4.632410e-04,0.000256,0.000503,cpd00367
2,Cytosine,cpd00307,HMDB0000630,Y,5.700000e-07,0.000000,5.700000e-07,0.000000,produced,5.700000e-07,5.700000e-07,0.000000,0.000000,cpd00307
3,Deoxyguanosine,cpd00277,HMDB0000085,Y,1.591738e-04,0.000159,4.741676e-04,0.000571,produced,1.591738e-04,4.741676e-04,0.000159,0.000571,cpd00277
4,Deoxyuridine,cpd00412,HMDB0000012,Y,1.752750e-05,0.000016,4.067860e-04,0.000598,produced,1.752750e-05,4.067860e-04,0.000016,0.000598,cpd00412

## Simulating with the given SD

In [5]:
output_1 = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='gurobi', productionRate=productionRate)

'180_genome' is not a valid SBML 'SId'.

Set parameter Username
Academic license - for non-commercial use only - expires 2026-02-21

'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpo1xvga89.lp
Reading time = 0.03 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpx5fb3en5.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp_6rx05f7.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpkk45ey_n.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpwzktsl26.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp75lh7kbq.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp26a7in7x.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmplqlezkny.lp
Reading time = 0.03 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model

c:\Users\Admin\anaconda3\envs\com_modelling\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

Optimization is done
Comparing the actual and predicted biomass weights
                        Model   Predicted    Actual
0     Lachnospiraceae_species  143.869775  0.000001
1          Bacteroides_ovatus    1.000000  0.008976
2      Bifidobacterium_longum    0.000000  0.000124
3     Collinsella_aerofaciens   33.844141  0.000007
4            Escherichia_coli   -3.666882  0.000085
5        Klebsiella_aerogenes    0.016187  0.000121
6         Muricomes_intestini    1.000000  0.000082
7  Parabacteroides_distasonis -176.053400  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite    Predicted    Actual
0    cpd00311     0.000326  0.000426
1    cpd00051    48.958750  0.010031
2    cpd00132     0.003727  0.013742
3    cpd00053    -0.001504  0.010734
4    cpd00033  -848.891871  0.012528
5    cpd00119  -865.754580  0.002745
6    cpd00359 -4591.660586  0.000025
7    cpd00039  -438.154500  0.012356
8    cpd00054  3281.909583  0.008564
9    cpd00161   695.612711  0.025882
10   cpd00065  -963.413091  0.000111
11   cpd00156 -5177.181366  0.005087
12   cpd00211    -0.000835  0.000765
13   cpd00300     0.000029  0.000111
Comparing the actual and predicted metabolomics production rates by the community
   Metabolite    Predicted    Actual
0    cpd00182   746.010151  0.000065
1    cpd00367 -4869.227104  0.000289
2    cpd00307    -0.632707  0.000000
3    cpd00277  -723.740771  0.000563
4    cpd00412  3284.071143  0.000695
5    cpd00246 -1663.345113  0.000657
6    cpd00184    -0.044084  0.001893
7    cpd00092  2923.719805  0.000789
8    cpd00152     0.000000  0.000068
9    cpd00035  3610.887031  0.013445
10   cpd00041 -6423.424617  0.019429
11   cpd00098     0.062055  0.000684
12   cpd00281  1854.090720  0.000825
13   cpd00023 -1212.693992  0.021468
14   cpd00322    90.600748  0.000373
15   cpd00107  -152.060297  0.001371
16   cpd00060 -1280.590597  0.004294
17   cpd00064   138.721054  0.001065
18   cpd00066   336.788761  0.005507
19   cpd00129 -1626.691767  0.018991
20   cpd00118   -55.750283  0.005537
21   cpd00264   530.816344  0.004111
22   cpd00210   253.915515  0.032717
23   cpd00069 -5591.119837  0.002608
24   cpd00249   547.702253  0.000029
25   cpd00136    -0.124259  0.000040
26   cpd00489     0.000000  0.000246
27   cpd00029  6980.067015  0.863993
28   cpd00153     0.000000  0.000024
29   cpd00137     0.000000  0.000062
30   cpd00106   691.006936  0.047816
31   cpd00159     0.000000  0.019044
32   cpd00221  1243.867627  0.019044
33   cpd00130  4858.109701  0.018638
34   cpd00141  1697.408056  0.172798
35   cpd00020   759.755440  0.003459
36   cpd00036  1556.925896  0.167730
37   cpd00309   553.617848  0.007155
38   cpd01217     0.000000  0.000099
39   cpd00027   355.440626  0.036887

c:\Users\Admin\anaconda3\envs\com_modelling\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)
c:\Users\Admin\anaconda3\envs\com_modelling\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

# Increasing the bounds by taking 2 times the standard deviation

In [6]:
output_2 = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='gurobi', n_sd =2, productionRate=productionRate)

'180_genome' is not a valid SBML 'SId'.
'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmppv_bgbrt.lp
Reading time = 0.02 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpkjy8ah6a.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp398e_eb9.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp01rduuqx.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpq63y8mt7.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp0prmficc.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpzi8v_ffu.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpxdee1h_3.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model
Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.000000  0.008976
2      Bifidobacterium_longum   0.000000  0.000124
3     Collinsella_aerofaciens   0.000000  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.009737  0.000121
6         Muricomes_intestini   0.000000  0.000082
7  Parabacteroides_distasonis   0.000000  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00311  -0.000000  0.000426
1    cpd00051   0.019644  0.010031
2    cpd00132  -0.000000  0.013742
3    cpd00053  -0.000000  0.010734
4    cpd00033   0.000157  0.012528
5    cpd00119   0.001578  0.002745
6    cpd00359  -0.000000  0.000025
7    cpd00039   0.005714  0.012356
8    cpd00054   0.000065  0.008564
9    cpd00161   0.019511  0.025882
10   cpd00065   0.000947  0.000111
11   cpd00156   0.007047  0.005087
12   cpd00211  -0.000000  0.000765
13   cpd00300  -0.000000  0.000111
Comparing the actual and predicted metabolomics production rates by the community
   Metabolite  Predicted    Actual
0    cpd00182   0.000000  0.000065
1    cpd00367   0.000000  0.000289
2    cpd00307   0.000000  0.000000
3    cpd00277   0.000000  0.000563
4    cpd00412   0.000000  0.000695
5    cpd00246   0.000000  0.000657
6    cpd00184   0.000000  0.001893
7    cpd00092   0.000000  0.000789
8    cpd00152   0.000000  0.000068
9    cpd00035  -0.011779  0.013445
10   cpd00041  -0.026728  0.019429
11   cpd00098   0.000000  0.000684
12   cpd00281   0.000100  0.000825
13   cpd00023  -0.000089  0.021468
14   cpd00322  -0.004849  0.000373
15   cpd00107  -0.008962  0.001371
16   cpd00060  -0.002856  0.004294
17   cpd00064   0.004375  0.001065
18   cpd00066  -0.003085  0.005507
19   cpd00129  -0.003681  0.018991
20   cpd00118   0.000000  0.005537
21   cpd00264   0.000000  0.004111
22   cpd00210   0.000000  0.032717
23   cpd00069  -0.002296  0.002608
24   cpd00249   0.000000  0.000029
25   cpd00136   0.000000  0.000040
26   cpd00489   0.000000  0.000246
27   cpd00029   0.009849  0.863993
28   cpd00153   0.000000  0.000024
29   cpd00137   0.000000  0.000062
30   cpd00106   0.000000  0.047816
31   cpd00159   0.000000  0.019044
32   cpd00221   0.000000  0.019044
33   cpd00130   0.000000  0.018638
34   cpd00141   0.000000  0.172798
35   cpd00020   0.000000  0.003459
36   cpd00036   0.013693  0.167730
37   cpd00309   0.000000  0.007155
38   cpd01217   0.000000  0.000099
39   cpd00027   0.000000  0.036887

In [ ]:
# setting a relaxation on the total biomass constraint
output_2 = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='gurobi', n_sd =2, productionRate=productionRate,alpha=100)

'180_genome' is not a valid SBML 'SId'.
'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpo6daodye.lp
Reading time = 0.02 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpp8ihypt7.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpt4f0s4g8.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmplooe2vuo.lp
Reading time = 0.01 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpj5lpdvxu.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpd7dnprdd.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpz3mv1lxs.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpjfmiqh28.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model
Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.000000  0.008976
2      Bifidobacterium_longum   0.000000  0.000124
3     Collinsella_aerofaciens   0.000007  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.000121  0.000121
6         Muricomes_intestini   0.000000  0.000082
7  Parabacteroides_distasonis   0.000000  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00311  -0.000000  0.000426
1    cpd00051   0.000386  0.010031
2    cpd00132  -0.000000  0.013742
3    cpd00053  -0.000000  0.010734
4    cpd00033   0.000363  0.012528
5    cpd00119   0.000034  0.002745
6    cpd00359  -0.000000  0.000025
7    cpd00039   0.000317  0.012356
8    cpd00054   0.000622  0.008564
9    cpd00161   0.000303  0.025882
10   cpd00065   0.000021  0.000111
11   cpd00156   0.000152  0.005087
12   cpd00211  -0.000302  0.000765
13   cpd00300   0.000002  0.000111
Comparing the actual and predicted metabolomics production rates by the community
   Metabolite  Predicted    Actual
0    cpd00182   0.000000  0.000065
1    cpd00367   0.000010  0.000289
2    cpd00307   0.000000  0.000000
3    cpd00277   0.000000  0.000563
4    cpd00412   0.000000  0.000695
5    cpd00246   0.000000  0.000657
6    cpd00184   0.000000  0.001893
7    cpd00092   0.000000  0.000789
8    cpd00152   0.000000  0.000068
9    cpd00035  -0.000206  0.013445
10   cpd00041  -0.000848  0.019429
11   cpd00098   0.000000  0.000684
12   cpd00281   0.000000  0.000825
13   cpd00023  -0.000762  0.021468
14   cpd00322  -0.000130  0.000373
15   cpd00107  -0.000194  0.001371
16   cpd00060  -0.000067  0.004294
17   cpd00064   0.000007  0.001065
18   cpd00066  -0.000067  0.005507
19   cpd00129  -0.000077  0.018991
20   cpd00118   0.000180  0.005537
21   cpd00264   0.000000  0.004111
22   cpd00210   0.000000  0.032717
23   cpd00069  -0.000050  0.002608
24   cpd00249   0.000000  0.000029
25   cpd00136   0.000000  0.000040
26   cpd00489   0.000000  0.000246
27   cpd00029   0.015489  0.863993
28   cpd00153   0.000000  0.000024
29   cpd00137   0.000000  0.000062
30   cpd00106   0.000000  0.047816
31   cpd00159   0.000000  0.019044
32   cpd00221   0.000000  0.019044
33   cpd00130   0.000931  0.018638
34   cpd00141   0.000021  0.172798
35   cpd00020   0.000000  0.003459
36   cpd00036   0.004907  0.167730
37   cpd00309   0.000000  0.007155
38   cpd01217   0.000000  0.000099
39   cpd00027   0.000000  0.036887

# Simulating the community model by adding a beta variable to the metabolomics constraint. Also, the objective function will have a term for summation of all betas.

In [7]:
output_3 = simulateCommunityModel_with_beta(modelDetails, exchangeRate, mu, solver='gurobi', productionRate=productionRate)

'180_genome' is not a valid SBML 'SId'.
'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpur9vsag_.lp
Reading time = 0.02 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpv2510z3r.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpi0_t0nbn.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpd8sd8w75.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpj21ot5vw.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmptgb2urh4.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmps1nou0tm.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp3xx2g53l.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model
Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.000000  0.008976
2      Bifidobacterium_longum   0.000000  0.000124
3     Collinsella_aerofaciens   0.000000  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.009737  0.000121
6         Muricomes_intestini   0.000000  0.000082
7  Parabacteroides_distasonis   0.000000  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00311  -0.000000  0.000426
1    cpd00051   0.010031  0.010031
2    cpd00132  -0.000000  0.013742
3    cpd00053  -0.000000  0.010734
4    cpd00033   0.012528  0.012528
5    cpd00119   0.001578  0.002745
6    cpd00359  -0.000000  0.000025
7    cpd00039   0.012356  0.012356
8    cpd00054   0.008564  0.008564
9    cpd00161   0.019644  0.025882
10   cpd00065   0.000111  0.000111
11   cpd00156   0.005087  0.005087
12   cpd00211   0.000765  0.000765
13   cpd00300  -0.000000  0.000111
Comparing the actual and predicted metabolomics production rates by the community
   Metabolite  Predicted    Actual
0    cpd00182   0.000000  0.000065
1    cpd00367   0.000000  0.000289
2    cpd00307   0.000000  0.000000
3    cpd00277   0.000000  0.000563
4    cpd00412   0.000000  0.000695
5    cpd00246   0.000000  0.000657
6    cpd00184   0.000000  0.001893
7    cpd00092   0.000000  0.000789
8    cpd00152   0.000000  0.000068
9    cpd00035  -0.005250  0.013445
10   cpd00041  -0.025366  0.019429
11   cpd00098   0.000000  0.000684
12   cpd00281   0.004940  0.000825
13   cpd00023  -0.010990  0.021468
14   cpd00322  -0.004796  0.000373
15   cpd00107  -0.008962  0.001371
16   cpd00060  -0.004127  0.004294
17   cpd00064   0.000000  0.001065
18   cpd00066  -0.003085  0.005507
19   cpd00129  -0.003681  0.018991
20   cpd00118   0.000289  0.005537
21   cpd00264   0.000000  0.004111
22   cpd00210   0.000000  0.032717
23   cpd00069  -0.002296  0.002608
24   cpd00249   0.000000  0.000029
25   cpd00136   0.000000  0.000040
26   cpd00489   0.000000  0.000246
27   cpd00029   0.000557  0.863993
28   cpd00153   0.000000  0.000024
29   cpd00137   0.000000  0.000062
30   cpd00106   0.011242  0.047816
31   cpd00159   0.954567  0.019044
32   cpd00221   0.000000  0.019044
33   cpd00130   0.000000  0.018638
34   cpd00141   0.000078  0.172798
35   cpd00020   0.000000  0.003459
36   cpd00036   0.005435  0.167730
37   cpd00309   0.000000  0.007155
38   cpd01217   0.000000  0.000099
39   cpd00027   0.000000  0.036887

In [7]:
output_3 = simulateCommunityModel_with_beta(modelDetails, exchangeRate, 2, solver='gurobi', productionRate=productionRate,tradeoff=0.5)

'180_genome' is not a valid SBML 'SId'.
'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp3xghoox7.lp
Reading time = 0.02 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpls9376cd.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp676uy4jk.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp0eeb4uka.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpuungzehu.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpq9ml5fr4.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpp1r4gmm6.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp8hbz4qjn.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model
Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.000000  0.008976
2      Bifidobacterium_longum   0.000000  0.000124
3     Collinsella_aerofaciens   0.000000  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.009737  0.000121
6         Muricomes_intestini   0.000000  0.000082
7  Parabacteroides_distasonis   0.000000  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00311  -0.000000  0.000477
1    cpd00051   0.011233  0.011233
2    cpd00132  -0.000000  0.015389
3    cpd00053  -0.000000  0.012020
4    cpd00033   0.014029  0.014029
5    cpd00119   0.001767  0.003074
6    cpd00359  -0.000000  0.000028
7    cpd00039   0.013837  0.013837
8    cpd00054   0.009590  0.009590
9    cpd00161   0.019644  0.028984
10   cpd00065   0.000124  0.000124
11   cpd00156   0.005696  0.005696
12   cpd00211   0.000857  0.000857
13   cpd00300  -0.000000  0.000125
Comparing the actual and predicted metabolomics production rates by the community
   Metabolite  Predicted    Actual
0    cpd00182   0.000000  0.000073
1    cpd00367   0.000000  0.000324
2    cpd00307   0.000000  0.000000
3    cpd00277   0.000000  0.000630
4    cpd00412   0.000000  0.000779
5    cpd00246   0.000000  0.000735
6    cpd00184   0.000000  0.002120
7    cpd00092   0.000000  0.000883
8    cpd00152   0.000000  0.000077
9    cpd00035  -0.029303  0.015056
10   cpd00041  -0.031224  0.021757
11   cpd00098   0.000000  0.000766
12   cpd00281   0.000000  0.000924
13   cpd00023  -0.000100  0.024041
14   cpd00322  -0.000061  0.000418
15   cpd00107  -0.010036  0.001536
16   cpd00060  -0.003256  0.004809
17   cpd00064   0.005534  0.001192
18   cpd00066  -0.003455  0.006166
19   cpd00129  -0.004122  0.021267
20   cpd00118   0.000000  0.006200
21   cpd00264   0.000000  0.004604
22   cpd00210   0.000000  0.036637
23   cpd00069  -0.002571  0.002920
24   cpd00249   0.000000  0.000033
25   cpd00136   0.000000  0.000044
26   cpd00489   0.000000  0.000276
27   cpd00029   0.923238  0.967517
28   cpd00153   0.000000  0.000027
29   cpd00137   0.010701  0.000069
30   cpd00106   0.000000  0.053545
31   cpd00159   0.083975  0.021326
32   cpd00221   0.008074  0.021326
33   cpd00130   0.000000  0.020872
34   cpd00141   0.000126  0.193503
35   cpd00020   0.000000  0.003873
36   cpd00036   0.000530  0.187827
37   cpd00309   0.000000  0.008013
38   cpd01217   0.000000  0.000110
39   cpd00027  -0.000170  0.041307