In [1]:
from scripts.python.simulateCommunityModel import simulateCommunityModel
from scripts.python.simulateCommunityModel_with_beta import simulateCommunityModel_with_beta
import pandas as pd

In [2]:
mu = 1 # growth rate
modelNames = ['Lachnospiraceae_species','Bacteroides_ovatus','Bifidobacterium_longum',
'Collinsella_aerofaciens','Escherichia_coli','Klebsiella_aerogenes','Muricomes_intestini','Parabacteroides_distasonis']
modelPaths = ['./Data/HDC/HDC1_gapseq/HDC_180_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_376_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_370_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_374_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_382_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_bin1.xml',
'./Data/HDC/HDC1_gapseq/HDC_380_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_378_genome.xml']
modelWeights = [0.000001,0.008976,0.000124,0.000007,0.000085,0.000121,0.000082,0.000426]

modelDetails = pd.DataFrame({'Name':modelNames,'Path':modelPaths,'weight':modelWeights})
modelDetails.head()

,Name,Path,weight
0,Lachnospiraceae_species,./Data/HDC/HDC1_gapseq/HDC_180_genome.xml,0.000001
1,Bacteroides_ovatus,./Data/HDC/HDC1_gapseq/HDC_376_genome.xml,0.008976
2,Bifidobacterium_longum,./Data/HDC/HDC1_gapseq/HDC_370_genome.xml,0.000124
3,Collinsella_aerofaciens,./Data/HDC/HDC1_gapseq/HDC_374_genome.xml,0.000007
4,Escherichia_coli,./Data/HDC/HDC1_gapseq/HDC_382_genome.xml,0.000085

In [3]:
# exchange reactions (from metabolomics data)
exchangeRate = pd.read_excel('./Data/HDC/HDC1_metabolomics_preliminary_formodelling2.xlsx')
exchangeRate['GF_conc'] = exchangeRate['GF_Mean (mmol per g)']
exchangeRate['Microbiome_conc'] = exchangeRate['HDC1_Mean (mmol per g)']
exchangeRate['GF_conc_sd'] = exchangeRate['GF_Standard deviation (mmol per g)']
exchangeRate['Microbiome_conc_sd'] = exchangeRate['HDC1_Standard deviation (mmol per g)']
exchangeRate['metabolite ID'] = exchangeRate['modelseed ID']
exchangeRate.head()

,Quantified compounds,modelseed ID,HMDB ID,Metabolite present in gapseq model exchange reactions?,GF_Mean (mmol per g),GF_Standard deviation (mmol per g),HDC1_Mean (mmol per g),HDC1_Standard deviation (mmol per g),Consumed or produced?,GF_conc,Microbiome_conc,GF_conc_sd,Microbiome_conc_sd,metabolite ID
0,Guanosine,cpd00311,HMDB0000133,Y,0.000523,0.000386,0.000284,0.000330,consumed,0.000523,0.000284,0.000386,0.000330,cpd00311
1,Argnine,cpd00051,HMDB0000517,Y,0.007678,0.006080,0.002062,0.001895,consumed,0.007678,0.002062,0.006080,0.001895,cpd00051
2,Asparagine,cpd00132,HMDB0000168,Y,0.007764,0.005528,0.000069,0.000080,consumed,0.007764,0.000069,0.005528,0.000080,cpd00132
3,Glutamine,cpd00053,HMDB0000641,Y,0.008064,0.005168,0.002055,0.001684,consumed,0.008064,0.002055,0.005168,0.001684,cpd00053
4,Glycine,cpd00033,HMDB0000123,Y,0.015165,0.011155,0.008150,0.006380,consumed,0.015165,0.008150,0.011155,0.006380,cpd00033

## Simulating with the given SD

In [ ]:
solution = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='gurobi')

'180_genome' is not a valid SBML 'SId'.

Set parameter Username
Academic license - for non-commercial use only - expires 2026-02-21

'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpramql4yv.lp
Reading time = 0.03 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpa3cuaqut.lp
Reading time = 0.03 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpmifgy3ix.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp49e4sbzj.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp5bi8n34f.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp2vfb5826.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpm2oefr55.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp0to5jqqb.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model

c:\Users\Admin\anaconda3\envs\com_modelling\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.009311  0.008976
2      Bifidobacterium_longum   0.000000  0.000124
3     Collinsella_aerofaciens   0.000000  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.000000  0.000121
6         Muricomes_intestini   0.000000  0.000082
7  Parabacteroides_distasonis   0.000426  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00311  -0.000000  0.000238
1    cpd00051   0.003636  0.005617
2    cpd00132   0.002087  0.007694
3    cpd00053  -0.000842  0.006010
4    cpd00033  -0.010521  0.007014
5    cpd00119   0.009357  0.001537
6    cpd00359   0.000041  0.000014
7    cpd00039   0.016177  0.006918
8    cpd00054   0.029466  0.004795
9    cpd00161   0.019588  0.014492
10   cpd00065   0.000489  0.000062
11   cpd00156  -0.041292  0.002848
12   cpd00211  -0.000467  0.000429
13   cpd00300   0.000135  0.000062

c:\Users\Admin\anaconda3\envs\com_modelling\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

# Increasing the bounds by taking 2 times the standard deviation

In [4]:
solution = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='gurobi', n_sd =2)

'180_genome' is not a valid SBML 'SId'.

Set parameter Username
Academic license - for non-commercial use only - expires 2026-02-21

'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpxtfqam0f.lp
Reading time = 0.02 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp82hrftrs.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmplcbo6z48.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpw6t__cml.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp58w0zbq8.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp39fkluqs.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmptih9ix3r.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpjrzpxpvb.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model
Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.008976  0.008976
2      Bifidobacterium_longum   0.000124  0.000124
3     Collinsella_aerofaciens   0.000007  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.000121  0.000121
6         Muricomes_intestini   0.000082  0.000082
7  Parabacteroides_distasonis   0.000427  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite     Predicted    Actual
0    cpd00311 -0.000000e+00  0.000238
1    cpd00051  3.788249e-03  0.005617
2    cpd00132 -0.000000e+00  0.007694
3    cpd00053 -2.895000e-04  0.006010
4    cpd00033  6.654536e-04  0.007014
5    cpd00119  8.844031e-04  0.001537
6    cpd00359 -0.000000e+00  0.000014
7    cpd00039  3.207514e-03  0.006918
8    cpd00054  2.236643e-02  0.004795
9    cpd00161  2.782932e-03  0.014492
10   cpd00065  5.319584e-04  0.000062
11   cpd00156 -4.219853e-03  0.002848
12   cpd00211  7.244441e-07  0.000429
13   cpd00300 -8.401341e-05  0.000062

# Simulation the community model by adding a beta variable to the metabolomics constraint. Also, the objective function will have a term for summation of all betas.

In [4]:
solution = simulateCommunityModel_with_beta(modelDetails, exchangeRate, mu, solver='gurobi')

'180_genome' is not a valid SBML 'SId'.

Set parameter Username
Academic license - for non-commercial use only - expires 2026-02-21

'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpr0fdgjm8.lp
Reading time = 0.01 seconds
: 1454 rows, 3396 columns, 14966 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp4gg2ckq6.lp
Reading time = 0.02 seconds
: 1661 rows, 4098 columns, 17964 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp91n2a7pk.lp
Reading time = 0.02 seconds
: 1355 rows, 3320 columns, 14560 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpv64stpem.lp
Reading time = 0.02 seconds
: 1177 rows, 2698 columns, 12056 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmp0_7mhdt7.lp
Reading time = 0.03 seconds
: 2357 rows, 6008 columns, 26634 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpv2zgrzt3.lp
Reading time = 0.03 seconds
: 2496 rows, 6336 columns, 28390 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpplh21fb1.lp
Reading time = 0.02 seconds
: 1733 rows, 4184 columns, 18524 nonzeros
Read LP format model from file C:\Users\Admin\AppData\Local\Temp\tmpssvvb9qy.lp
Reading time = 0.02 seconds
: 1670 rows, 4088 columns, 18026 nonzeros
Models are merged
Lower and upper bounds are updated based on the biomass weights
Biomass flux constraints are added based on the growth rate
Total biomass constraint is added
Metabolomics constraints are added
Absolute value constraints are added that are needed for the objective function
Optimizing the model
Optimization is done
Comparing the actual and predicted biomass weights
                        Model  Predicted    Actual
0     Lachnospiraceae_species   0.000000  0.000001
1          Bacteroides_ovatus   0.008976  0.008976
2      Bifidobacterium_longum   0.000124  0.000124
3     Collinsella_aerofaciens   0.000007  0.000007
4            Escherichia_coli   0.000085  0.000085
5        Klebsiella_aerogenes   0.000122  0.000121
6         Muricomes_intestini   0.000082  0.000082
7  Parabacteroides_distasonis   0.000426  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00311  -0.000000  0.000238
1    cpd00051   0.005617  0.005617
2    cpd00132  -0.000000  0.007694
3    cpd00053  -0.000000  0.006010
4    cpd00033   0.007014  0.007014
5    cpd00119   0.001537  0.001537
6    cpd00359  -0.000000  0.000014
7    cpd00039   0.003566  0.006918
8    cpd00054   0.004795  0.004795
9    cpd00161   0.014492  0.014492
10   cpd00065   0.000062  0.000062
11   cpd00156   0.002848  0.002848
12   cpd00211   0.000129  0.000429
13   cpd00300   0.000062  0.000062