In [1]:
from cobra.io import load_model
import cobra

In [2]:
cobra_config = cobra.Configuration()
cobra_config.solver = 'glpk'

In [50]:
model = load_model("textbook")

In [9]:
model.reactions.ATPM

In [51]:
len(model.constraints)

72

In [52]:
coefficients = dict()
for rxn in model.reactions:
    coefficients[rxn.forward_variable] = 1.
    coefficients[rxn.reverse_variable] = 1.
constraint = model.problem.Constraint(12,name='tp', lb=0, ub=10000)
model.add_cons_vars(constraint)
model.solver.update()
constraint.set_linear_coefficients(coefficients=coefficients)

In [54]:
solution = model.optimize()
solution.to_frame()
solution.fluxes.abs().sum()

518.4220855176067

In [58]:
model.reactions.EX_glc__D_e

In [62]:
model.summary()

In [63]:
# renaming all the reactions in the model
model2 = model.copy()
for rxn in model2.reactions:
    rxn.id = rxn.id + "_2"

In [64]:
model2.reactions

[<Reaction ACALD_2 at 0x1dde0163fa0>,
 <Reaction ACALDt_2 at 0x1dde01614e0>,
 <Reaction ACKr_2 at 0x1dde0161270>,
 <Reaction ACONTa_2 at 0x1dde01613c0>,
 <Reaction ACONTb_2 at 0x1dd9a1bef50>,
 <Reaction ACt2r_2 at 0x1dddf01add0>,
 <Reaction ADK1_2 at 0x1dde0161390>,
 <Reaction AKGDH_2 at 0x1dde0163910>,
 <Reaction AKGt2r_2 at 0x1dde0163e80>,
 <Reaction ALCD2x_2 at 0x1dde00dca30>,
 <Reaction ATPM_2 at 0x1dde00dc1f0>,
 <Reaction ATPS4r_2 at 0x1dde00dcb50>,
 <Reaction Biomass_Ecoli_core_2 at 0x1dde00dead0>,
 <Reaction CO2t_2 at 0x1dde00dcd60>,
 <Reaction CS_2 at 0x1dde00dfc70>,
 <Reaction CYTBD_2 at 0x1dde00dc820>,
 <Reaction D_LACt2_2 at 0x1dde00de3b0>,
 <Reaction ENO_2 at 0x1dde00ddab0>,
 <Reaction ETOHt2r_2 at 0x1dde0194460>,
 <Reaction EX_ac_e_2 at 0x1dde0194580>,
 <Reaction EX_acald_e_2 at 0x1dde01946a0>,
 <Reaction EX_akg_e_2 at 0x1dde0194be0>,
 <Reaction EX_co2_e_2 at 0x1dde0194d00>,
 <Reaction EX_etoh_e_2 at 0x1dde0194dc0>,
 <Reaction EX_for_e_2 at 0x1dde0194e80>,
 <Reaction EX_fru_e_2 at 0x1dde0194f40>,
 <Reaction EX_fum_e_2 at 0x1dde0195000>,
 <Reaction EX_glc__D_e_2 at 0x1dde01950c0>,
 <Reaction EX_gln__L_e_2 at 0x1dde0195180>,
 <Reaction EX_glu__L_e_2 at 0x1dde0195240>,
 <Reaction EX_h_e_2 at 0x1dde0195300>,
 <Reaction EX_h2o_e_2 at 0x1dde01953c0>,
 <Reaction EX_lac__D_e_2 at 0x1dde0195480>,
 <Reaction EX_mal__L_e_2 at 0x1dde0195540>,
 <Reaction EX_nh4_e_2 at 0x1dde0195600>,
 <Reaction EX_o2_e_2 at 0x1dde01956c0>,
 <Reaction EX_pi_e_2 at 0x1dde0195780>,
 <Reaction EX_pyr_e_2 at 0x1dde0195840>,
 <Reaction EX_succ_e_2 at 0x1dde0195900>,
 <Reaction FBA_2 at 0x1dde01959c0>,
 <Reaction FBP_2 at 0x1dde0195a80>,
 <Reaction FORt2_2 at 0x1dde0195b40>,
 <Reaction FORti_2 at 0x1dde0194910>,
 <Reaction FRD7_2 at 0x1dde0195c00>,
 <Reaction FRUpts2_2 at 0x1dde0195cc0>,
 <Reaction FUM_2 at 0x1dde0195ed0>,
 <Reaction FUMt2_2_2 at 0x1dde01960b0>,
 <Reaction G6PDH2r_2 at 0x1dde0196290>,
 <Reaction GAPD_2 at 0x1dde0196470>,
 <Reaction GLCpts_2 at 0x1dde01966b0>,
 <Reaction GLNS_2 at 0x1dde0196920>,
 <Reaction GLNabc_2 at 0x1dde0196b30>,
 <Reaction GLUDy_2 at 0x1dde0196c50>,
 <Reaction GLUN_2 at 0x1dde0196d70>,
 <Reaction GLUSy_2 at 0x1dde0196e90>,
 <Reaction GLUt2r_2 at 0x1dde0197280>,
 <Reaction GND_2 at 0x1dde0197610>,
 <Reaction H2Ot_2 at 0x1dde0197820>,
 <Reaction ICDHyr_2 at 0x1dde0197940>,
 <Reaction ICL_2 at 0x1dde0197b50>,
 <Reaction LDH_D_2 at 0x1dde0197d30>,
 <Reaction MALS_2 at 0x1dde0197e50>,
 <Reaction MALt2_2_2 at 0x1dde0197f70>,
 <Reaction MDH_2 at 0x1dde01ac190>,
 <Reaction ME1_2 at 0x1dde01ac2b0>,
 <Reaction ME2_2 at 0x1dde01ac3d0>,
 <Reaction NADH16_2 at 0x1dde01ac5b0>,
 <Reaction NADTRHD_2 at 0x1dde01ac790>,
 <Reaction NH4t_2 at 0x1dde01ac8b0>,
 <Reaction O2t_2 at 0x1dde01ac9d0>,
 <Reaction PDH_2 at 0x1dde01acaf0>,
 <Reaction PFK_2 at 0x1dde01acc10>,
 <Reaction PFL_2 at 0x1dde01ad000>,
 <Reaction PGI_2 at 0x1dde01ad210>,
 <Reaction PGK_2 at 0x1dde01ad480>,
 <Reaction PGL_2 at 0x1dde01ad5a0>,
 <Reaction PGM_2 at 0x1dde01ad7b0>,
 <Reaction PIt2r_2 at 0x1dde01ad990>,
 <Reaction PPC_2 at 0x1dde01ade10>,
 <Reaction PPCK_2 at 0x1dde01ae020>,
 <Reaction PPS_2 at 0x1dde01ae140>,
 <Reaction PTAr_2 at 0x1dde01ae260>,
 <Reaction PYK_2 at 0x1dde01ae470>,
 <Reaction PYRt2_2 at 0x1dde01ae650>,
 <Reaction RPE_2 at 0x1dde01ae770>,
 <Reaction RPI_2 at 0x1dde01ae890>,
 <Reaction SUCCt2_2_2 at 0x1dde01aeb90>,
 <Reaction SUCCt3_2 at 0x1dde01ae9b0>,
 <Reaction SUCDi_2 at 0x1dde01aed70>,
 <Reaction SUCOAS_2 at 0x1dde01aee30>,
 <Reaction TALA_2 at 0x1dde01af1f0>,
 <Reaction THD2_2 at 0x1dde01af010>,
 <Reaction TKT1_2 at 0x1dde01af310>,
 <Reaction TKT2_2 at 0x1dde01af3d0>,
 <Reaction TPI_2 at 0x1dde01af610>]

In [73]:
dir(c)

['_Constraint__check_valid_active_when',
 '_Constraint__check_valid_indicator_variable',
 '_INDICATOR_CONSTRAINT_SUPPORT',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__itruediv__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_active_when',
 '_canonicalize',
 '_check_valid_lower_bound',
 '_check_valid_upper_bound',
 '_expression',
 '_get_expression',
 '_index',
 '_indicator_variable',
 '_lb',
 '_name',
 '_problem',
 '_round_primal_to_bounds',
 '_substitute_variables',
 '_ub',
 '_validate_optimization_expression_name',
 'active_when',
 'clone',
 'dual',
 'expression',
 'from_json',
 'get_linear_coefficients',
 'indicator_variable',
 'is_Linear',
 'is_Quadratic',
 'lb',
 'name',
 'primal',
 'problem',
 'set_linear_coefficients',
 'to_json',
 'ub',
 'variables']

In [81]:
model.constraints[0].problem.to_json()

{'name': None,
 'variables': [{'name': 'ACALD', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACALD_reverse_fda2b', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACALDt', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACALDt_reverse_858fa',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ACKr', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACKr_reverse_b49c0', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACONTa', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACONTa_reverse_cad6d',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ACONTb', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACONTb_reverse_e198a',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ACt2r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ACt2r_reverse_64e05', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ADK1', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ADK1_reverse_a6f90', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'AKGDH', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'AKGDH_reverse_08bdc', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'AKGt2r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'AKGt2r_reverse_5d500',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ALCD2x', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ALCD2x_reverse_5d107',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ATPM', 'lb': 8.39, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ATPM_reverse_5b752', 'lb': 0, 'ub': 0, 'type': 'continuous'},
  {'name': 'ATPS4r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ATPS4r_reverse_64306',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'Biomass_Ecoli_core', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'Biomass_Ecoli_core_reverse_2cdba',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'CO2t', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'CO2t_reverse_7c42f', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'CS', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'CS_reverse_8d7e9', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'CYTBD', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'CYTBD_reverse_611ba', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'D_LACt2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'D_LACt2_reverse_d0dc8',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ENO', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ENO_reverse_40eea', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ETOHt2r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ETOHt2r_reverse_b3d52',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_ac_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_ac_e_reverse_0be96', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'EX_acald_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_acald_e_reverse_c096e',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_akg_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_akg_e_reverse_70d85',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_co2_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_co2_e_reverse_d0466',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_etoh_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_etoh_e_reverse_cc64f',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_for_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_for_e_reverse_23269',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_fru_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_fru_e_reverse_c3828',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_fum_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_fum_e_reverse_e3432',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_glc__D_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_glc__D_e_reverse_af641',
   'lb': 0,
   'ub': 10.0,
   'type': 'continuous'},
  {'name': 'EX_gln__L_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_gln__L_e_reverse_6a1a1',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_glu__L_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_glu__L_e_reverse_42f6c',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_h_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_h_e_reverse_3e0c5',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_h2o_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_h2o_e_reverse_3ced4',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_lac__D_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_lac__D_e_reverse_f95b4',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_mal__L_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_mal__L_e_reverse_af154',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_nh4_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_nh4_e_reverse_f9cc6',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_o2_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_o2_e_reverse_efa94',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_pi_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_pi_e_reverse_1fb09',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'EX_pyr_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_pyr_e_reverse_1f6de',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'EX_succ_e', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'EX_succ_e_reverse_a9039',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'FBA', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FBA_reverse_84806', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FBP', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FBP_reverse_bf2c9', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'FORt2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FORt2_reverse_89839', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'FORti', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FORti_reverse_18c06', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'FRD7', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FRD7_reverse_e0172', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'FRUpts2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FRUpts2_reverse_58d3a', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'FUM', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FUM_reverse_d3642', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FUMt2_2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'FUMt2_2_reverse_7b4b6', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'G6PDH2r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'G6PDH2r_reverse_19ddf',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'GAPD', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GAPD_reverse_459c1', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLCpts', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLCpts_reverse_a52ae', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'GLNS', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLNS_reverse_59581', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'GLNabc', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLNabc_reverse_1d82a', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'GLUDy', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLUDy_reverse_fa4e7', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLUN', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLUN_reverse_4ccdb', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'GLUSy', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLUSy_reverse_6a00f', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'GLUt2r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GLUt2r_reverse_3e88a',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'GND', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'GND_reverse_eec5c', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'H2Ot', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'H2Ot_reverse_aa560', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ICDHyr', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ICDHyr_reverse_7f84b',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'ICL', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ICL_reverse_2f27e', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'LDH_D', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'LDH_D_reverse_f8507', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'MALS', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'MALS_reverse_d7382', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'MALt2_2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'MALt2_2_reverse_a635f', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'MDH', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'MDH_reverse_ee52c', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ME1', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ME1_reverse_9736c', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'ME2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'ME2_reverse_2b0a2', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'NADH16', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'NADH16_reverse_330a2', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'NADTRHD', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'NADTRHD_reverse_49725', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'NH4t', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'NH4t_reverse_551ee', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'O2t', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'O2t_reverse_4d957', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PDH', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PDH_reverse_ca160', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PFK', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PFK_reverse_d24a6', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PFL', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PFL_reverse_af9ec', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PGI', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PGI_reverse_27efc', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PGK', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PGK_reverse_02696', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PGL', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PGL_reverse_2bb6b', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PGM', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PGM_reverse_fc9af', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PIt2r', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PIt2r_reverse_1cd61', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PPC', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PPC_reverse_e854a', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PPCK', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PPCK_reverse_2557d', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PPS', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PPS_reverse_1c319', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PTAr', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PTAr_reverse_fce15', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PYK', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PYK_reverse_bc8ff', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'PYRt2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'PYRt2_reverse_a6e24', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'RPE', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'RPE_reverse_a1b04', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'RPI', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'RPI_reverse_853a1', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'SUCCt2_2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'SUCCt2_2_reverse_206ca',
   'lb': 0,
   'ub': -0.0,
   'type': 'continuous'},
  {'name': 'SUCCt3', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'SUCCt3_reverse_7d82a', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'SUCDi', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'SUCDi_reverse_480f4', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'SUCOAS', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'SUCOAS_reverse_22958',
   'lb': 0,
   'ub': 1000.0,
   'type': 'continuous'},
  {'name': 'TALA', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'TALA_reverse_adfda', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'THD2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'THD2_reverse_f65dd', 'lb': 0, 'ub': -0.0, 'type': 'continuous'},
  {'name': 'TKT1', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'TKT1_reverse_a1021', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'TKT2', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'TKT2_reverse_7ebc7', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'TPI', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'},
  {'name': 'TPI_reverse_c2c3b', 'lb': 0, 'ub': 1000.0, 'type': 'continuous'}],
 'constraints': [{'name': '13dpg_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'PGK_reverse_02696'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'PGK'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'GAPD_reverse_459c1'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'GAPD'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': '2pg_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'PGM_reverse_fc9af'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'PGM'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ENO_reverse_40eea'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ENO'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': '3pg_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'PGM_reverse_fc9af'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'PGM'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'PGK_reverse_02696'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'PGK'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.496},
       {'type': 'Symbol', 'name': 'Biomass_Ecoli_core_reverse_2cdba'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.496},
       {'type': 'Symbol', 'name': 'Biomass_Ecoli_core'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': '6pgc_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'PGL_reverse_2bb6b'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'PGL'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'GND_reverse_eec5c'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'GND'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': '6pgl_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'PGL_reverse_2bb6b'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'PGL'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'G6PDH2r_reverse_19ddf'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'G6PDH2r'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': 'ac_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ACt2r_reverse_64e05'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ACt2r'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ACKr_reverse_b49c0'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ACKr'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': 'ac_e',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'EX_ac_e_reverse_0be96'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'EX_ac_e'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ACt2r_reverse_64e05'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ACt2r'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': 'acald_c',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ALCD2x_reverse_5d107'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ALCD2x'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ACALDt_reverse_858fa'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ACALDt'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'ACALD_reverse_fda2b'}]},
     {'type': 'Mul',
      'args': [{'type': 'Number', 'value': -1.0},
       {'type': 'Symbol', 'name': 'ACALD'}]}]},
   'lb': 0,
   'ub': 0,
   'indicator_variable': None,
   'active_when': 1},
  {'name': 'acald_e',
   'expression': {'type': 'Add',
    'args': [{'type': 'Mul',
      'args': [{'type': 'Number', 'value': 1.0},
       {'type': 'Symbol', 'name': 'EX_acald_e_reverse_c096e'}]},

In [72]:
for c in model2.constraints:
    print(c.expression)

1.0*GAPD_2 - 1.0*GAPD_2_reverse_ee85f + 1.0*PGK_2 - 1.0*PGK_2_reverse_f19c0
-1.0*ENO_2 + 1.0*ENO_2_reverse_504d6 - 1.0*PGM_2 + 1.0*PGM_2_reverse_245dd
-1.496*Biomass_Ecoli_core_2 + 1.496*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*PGK_2 + 1.0*PGK_2_reverse_f19c0 + 1.0*PGM_2 - 1.0*PGM_2_reverse_245dd
-1.0*GND_2 + 1.0*GND_2_reverse_13977 + 1.0*PGL_2 - 1.0*PGL_2_reverse_c9bff
1.0*G6PDH2r_2 - 1.0*G6PDH2r_2_reverse_29261 - 1.0*PGL_2 + 1.0*PGL_2_reverse_c9bff
-1.0*ACKr_2 + 1.0*ACKr_2_reverse_1d125 + 1.0*ACt2r_2 - 1.0*ACt2r_2_reverse_e4a0f
-1.0*ACt2r_2 + 1.0*ACt2r_2_reverse_e4a0f - 1.0*EX_ac_e_2 + 1.0*EX_ac_e_2_reverse_5d7e5
-1.0*ACALD_2 + 1.0*ACALD_2_reverse_e1a2f + 1.0*ACALDt_2 - 1.0*ACALDt_2_reverse_56955 + 1.0*ALCD2x_2 - 1.0*ALCD2x_2_reverse_809dd
-1.0*ACALDt_2 + 1.0*ACALDt_2_reverse_56955 - 1.0*EX_acald_e_2 + 1.0*EX_acald_e_2_reverse_7bc8d
1.0*ACALD_2 - 1.0*ACALD_2_reverse_e1a2f - 3.7478*Biomass_Ecoli_core_2 + 3.7478*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*CS_2 + 1.0*CS_2_reverse_d9dba - 1.0*MALS_2 + 1.0*MALS_2_reverse_e76be + 1.0*PDH_2 - 1.0*PDH_2_reverse_ca386 + 1.0*PFL_2 - 1.0*PFL_2_reverse_eed7a - 1.0*PTAr_2 + 1.0*PTAr_2_reverse_39042
1.0*ACONTa_2 - 1.0*ACONTa_2_reverse_b464e - 1.0*ACONTb_2 + 1.0*ACONTb_2_reverse_0eaf5
1.0*ACKr_2 - 1.0*ACKr_2_reverse_1d125 + 1.0*PTAr_2 - 1.0*PTAr_2_reverse_39042
1.0*ACKr_2 - 1.0*ACKr_2_reverse_1d125 + 2.0*ADK1_2 - 2.0*ADK1_2_reverse_1f1fe + 1.0*ATPM_2 - 1.0*ATPM_2_reverse_e9efb - 1.0*ATPS4r_2 + 1.0*ATPS4r_2_reverse_4b447 + 59.81*Biomass_Ecoli_core_2 - 59.81*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*GLNS_2 - 1.0*GLNS_2_reverse_5559c + 1.0*GLNabc_2 - 1.0*GLNabc_2_reverse_c912b + 1.0*PFK_2 - 1.0*PFK_2_reverse_ff38b + 1.0*PGK_2 - 1.0*PGK_2_reverse_f19c0 + 1.0*PPCK_2 - 1.0*PPCK_2_reverse_6323d - 1.0*PYK_2 + 1.0*PYK_2_reverse_c2760 + 1.0*SUCOAS_2 - 1.0*SUCOAS_2_reverse_15f9c
-1.0*AKGDH_2 + 1.0*AKGDH_2_reverse_7ed30 + 1.0*AKGt2r_2 - 1.0*AKGt2r_2_reverse_4d4f0 + 4.1182*Biomass_Ecoli_core_2 - 4.1182*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*GLUDy_2 - 1.0*GLUDy_2_reverse_5f7c0 - 1.0*GLUSy_2 + 1.0*GLUSy_2_reverse_8b8ce + 1.0*ICDHyr_2 - 1.0*ICDHyr_2_reverse_799d2
-1.0*AKGt2r_2 + 1.0*AKGt2r_2_reverse_4d4f0 - 1.0*EX_akg_e_2 + 1.0*EX_akg_e_2_reverse_b1d5e
-1.0*ADK1_2 + 1.0*ADK1_2_reverse_1f1fe + 1.0*PPS_2 - 1.0*PPS_2_reverse_2b10c
-1.0*ACKr_2 + 1.0*ACKr_2_reverse_1d125 - 1.0*ADK1_2 + 1.0*ADK1_2_reverse_1f1fe - 1.0*ATPM_2 + 1.0*ATPM_2_reverse_e9efb + 1.0*ATPS4r_2 - 1.0*ATPS4r_2_reverse_4b447 - 59.81*Biomass_Ecoli_core_2 + 59.81*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*GLNS_2 + 1.0*GLNS_2_reverse_5559c - 1.0*GLNabc_2 + 1.0*GLNabc_2_reverse_c912b - 1.0*PFK_2 + 1.0*PFK_2_reverse_ff38b - 1.0*PGK_2 + 1.0*PGK_2_reverse_f19c0 - 1.0*PPCK_2 + 1.0*PPCK_2_reverse_6323d - 1.0*PPS_2 + 1.0*PPS_2_reverse_2b10c + 1.0*PYK_2 - 1.0*PYK_2_reverse_c2760 - 1.0*SUCOAS_2 + 1.0*SUCOAS_2_reverse_15f9c
-1.0*ACONTa_2 + 1.0*ACONTa_2_reverse_b464e + 1.0*CS_2 - 1.0*CS_2_reverse_d9dba
1.0*AKGDH_2 - 1.0*AKGDH_2_reverse_7ed30 + 1.0*CO2t_2 - 1.0*CO2t_2_reverse_9d99f + 1.0*GND_2 - 1.0*GND_2_reverse_13977 + 1.0*ICDHyr_2 - 1.0*ICDHyr_2_reverse_799d2 + 1.0*ME1_2 - 1.0*ME1_2_reverse_63695 + 1.0*ME2_2 - 1.0*ME2_2_reverse_b92af + 1.0*PDH_2 - 1.0*PDH_2_reverse_ca386 + 1.0*PPCK_2 - 1.0*PPCK_2_reverse_6323d - 1.0*PPC_2 + 1.0*PPC_2_reverse_d78d7
-1.0*CO2t_2 + 1.0*CO2t_2_reverse_9d99f - 1.0*EX_co2_e_2 + 1.0*EX_co2_e_2_reverse_3c0c0
-1.0*ACALD_2 + 1.0*ACALD_2_reverse_e1a2f - 1.0*AKGDH_2 + 1.0*AKGDH_2_reverse_7ed30 + 3.7478*Biomass_Ecoli_core_2 - 3.7478*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*CS_2 - 1.0*CS_2_reverse_d9dba + 1.0*MALS_2 - 1.0*MALS_2_reverse_e76be - 1.0*PDH_2 + 1.0*PDH_2_reverse_ca386 - 1.0*PFL_2 + 1.0*PFL_2_reverse_eed7a + 1.0*PTAr_2 - 1.0*PTAr_2_reverse_39042 - 1.0*SUCOAS_2 + 1.0*SUCOAS_2_reverse_15f9c
1.0*FBA_2 - 1.0*FBA_2_reverse_bcfcc - 1.0*TPI_2 + 1.0*TPI_2_reverse_ccea1
-0.361*Biomass_Ecoli_core_2 + 0.361*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*TALA_2 - 1.0*TALA_2_reverse_a07de - 1.0*TKT2_2 + 1.0*TKT2_2_reverse_62491
-1.0*ALCD2x_2 + 1.0*ALCD2x_2_reverse_809dd + 1.0*ETOHt2r_2 - 1.0*ETOHt2r_2_reverse_8fe11
-1.0*ETOHt2r_2 + 1.0*ETOHt2r_2_reverse_8fe11 - 1.0*EX_etoh_e_2 + 1.0*EX_etoh_e_2_reverse_b40bf
-0.0709*Biomass_Ecoli_core_2 + 0.0709*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*FBP_2 - 1.0*FBP_2_reverse_40e3f + 1.0*FRUpts2_2 - 1.0*FRUpts2_2_reverse_8a962 - 1.0*PFK_2 + 1.0*PFK_2_reverse_ff38b + 1.0*PGI_2 - 1.0*PGI_2_reverse_3f620 + 1.0*TALA_2 - 1.0*TALA_2_reverse_a07de + 1.0*TKT2_2 - 1.0*TKT2_2_reverse_62491
-1.0*FBA_2 + 1.0*FBA_2_reverse_bcfcc - 1.0*FBP_2 + 1.0*FBP_2_reverse_40e3f + 1.0*PFK_2 - 1.0*PFK_2_reverse_ff38b
1.0*FORt2_2 - 1.0*FORt2_2_reverse_db98f - 1.0*FORti_2 + 1.0*FORti_2_reverse_ef2d5 + 1.0*PFL_2 - 1.0*PFL_2_reverse_eed7a
-1.0*EX_for_e_2 + 1.0*EX_for_e_2_reverse_6f6c8 - 1.0*FORt2_2 + 1.0*FORt2_2_reverse_db98f + 1.0*FORti_2 - 1.0*FORti_2_reverse_ef2d5
-1.0*EX_fru_e_2 + 1.0*EX_fru_e_2_reverse_71238 - 1.0*FRUpts2_2 + 1.0*FRUpts2_2_reverse_8a962
-1.0*FRD7_2 + 1.0*FRD7_2_reverse_73a9f - 1.0*FUM_2 + 1.0*FUM_2_reverse_83caf + 1.0*FUMt2_2_2 - 1.0*FUMt2_2_2_reverse_98895 + 1.0*SUCDi_2 - 1.0*SUCDi_2_reverse_10183
-1.0*EX_fum_e_2 + 1.0*EX_fum_e_2_reverse_e23c1 - 1.0*FUMt2_2_2 + 1.0*FUMt2_2_2_reverse_98895
-0.129*Biomass_Ecoli_core_2 + 0.129*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*FBA_2 - 1.0*FBA_2_reverse_bcfcc - 1.0*GAPD_2 + 1.0*GAPD_2_reverse_ee85f - 1.0*TALA_2 + 1.0*TALA_2_reverse_a07de + 1.0*TKT1_2 - 1.0*TKT1_2_reverse_f68af + 1.0*TKT2_2 - 1.0*TKT2_2_reverse_62491 + 1.0*TPI_2 - 1.0*TPI_2_reverse_ccea1
-0.205*Biomass_Ecoli_core_2 + 0.205*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*G6PDH2r_2 + 1.0*G6PDH2r_2_reverse_29261 + 1.0*GLCpts_2 - 1.0*GLCpts_2_reverse_bbdcb - 1.0*PGI_2 + 1.0*PGI_2_reverse_3f620
-1.0*EX_glc__D_e_2 + 1.0*EX_glc__D_e_2_reverse_f4e76 - 1.0*GLCpts_2 + 1.0*GLCpts_2_reverse_bbdcb
-0.2557*Biomass_Ecoli_core_2 + 0.2557*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*GLNS_2 - 1.0*GLNS_2_reverse_5559c + 1.0*GLNabc_2 - 1.0*GLNabc_2_reverse_c912b - 1.0*GLUN_2 + 1.0*GLUN_2_reverse_1f598 - 1.0*GLUSy_2 + 1.0*GLUSy_2_reverse_8b8ce
-1.0*EX_gln__L_e_2 + 1.0*EX_gln__L_e_2_reverse_e5e6c - 1.0*GLNabc_2 + 1.0*GLNabc_2_reverse_c912b
-4.9414*Biomass_Ecoli_core_2 + 4.9414*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*GLNS_2 + 1.0*GLNS_2_reverse_5559c - 1.0*GLUDy_2 + 1.0*GLUDy_2_reverse_5f7c0 + 1.0*GLUN_2 - 1.0*GLUN_2_reverse_1f598 + 2.0*GLUSy_2 - 2.0*GLUSy_2_reverse_8b8ce + 1.0*GLUt2r_2 - 1.0*GLUt2r_2_reverse_a1cdc
-1.0*EX_glu__L_e_2 + 1.0*EX_glu__L_e_2_reverse_9b53d - 1.0*GLUt2r_2 + 1.0*GLUt2r_2_reverse_a1cdc
1.0*ICL_2 - 1.0*ICL_2_reverse_5b4ec - 1.0*MALS_2 + 1.0*MALS_2_reverse_e76be
1.0*ACONTa_2 - 1.0*ACONTa_2_reverse_b464e - 1.0*ACONTb_2 + 1.0*ACONTb_2_reverse_0eaf5 - 1.0*ATPM_2 + 1.0*ATPM_2_reverse_e9efb + 1.0*ATPS4r_2 - 1.0*ATPS4r_2_reverse_4b447 - 59.81*Biomass_Ecoli_core_2 + 59.81*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*CS_2 + 1.0*CS_2_reverse_d9dba + 1.0*CYTBD_2 - 1.0*CYTBD_2_reverse_66ef2 + 1.0*ENO_2 - 1.0*ENO_2_reverse_504d6 - 1.0*FBP_2 + 1.0*FBP_2_reverse_40e3f - 1.0*FUM_2 + 1.0*FUM_2_reverse_83caf - 1.0*GLNabc_2 + 1.0*GLNabc_2_reverse_c912b - 1.0*GLUDy_2 + 1.0*GLUDy_2_reverse_5f7c0 - 1.0*GLUN_2 + 1.0*GLUN_2_reverse_1f598 + 1.0*H2Ot_2 - 1.0*H2Ot_2_reverse_1a867 - 1.0*MALS_2 + 1.0*MALS_2_reverse_e76be - 1.0*PGL_2 + 1.0*PGL_2_reverse_c9bff - 1.0*PPC_2 + 1.0*PPC_2_reverse_d78d7 - 1.0*PPS_2 + 1.0*PPS_2_reverse_2b10c
-1.0*EX_h2o_e_2 + 1.0*EX_h2o_e_2_reverse_b38e5 - 1.0*H2Ot_2 + 1.0*H2Ot_2_reverse_1a867
1.0*ACALD_2 - 1.0*ACALD_2_reverse_e1a2f + 1.0*ACt2r_2 - 1.0*ACt2r_2_reverse_e4a0f + 1.0*AKGt2r_2 - 1.0*AKGt2r_2_reverse_4d4f0 + 1.0*ALCD2x_2 - 1.0*ALCD2x_2_reverse_809dd + 1.0*ATPM_2 - 1.0*ATPM_2_reverse_e9efb + 3.0*ATPS4r_2 - 3.0*ATPS4r_2_reverse_4b447 + 59.81*Biomass_Ecoli_core_2 - 59.81*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*CS_2 - 1.0*CS_2_reverse_d9dba - 2.0*CYTBD_2 + 2.0*CYTBD_2_reverse_66ef2 + 1.0*D_LACt2_2 - 1.0*D_LACt2_2_reverse_a8152 + 1.0*ETOHt2r_2 - 1.0*ETOHt2r_2_reverse_8fe11 + 1.0*FORt2_2 - 1.0*FORt2_2_reverse_db98f + 2.0*FUMt2_2_2 - 2.0*FUMt2_2_2_reverse_98895 + 1.0*G6PDH2r_2 - 1.0*G6PDH2r_2_reverse_29261 + 1.0*GAPD_2 - 1.0*GAPD_2_reverse_ee85f + 1.0*GLNS_2 - 1.0*GLNS_2_reverse_5559c + 1.0*GLNabc_2 - 1.0*GLNabc_2_reverse_c912b + 1.0*GLUDy_2 - 1.0*GLUDy_2_reverse_5f7c0 - 1.0*GLUSy_2 + 1.0*GLUSy_2_reverse_8b8ce + 1.0*GLUt2r_2 - 1.0*GLUt2r_2_reverse_a1cdc + 1.0*LDH_D_2 - 1.0*LDH_D_2_reverse_daca6 + 1.0*MALS_2 - 1.0*MALS_2_reverse_e76be + 2.0*MALt2_2_2 - 2.0*MALt2_2_2_reverse_71b7e + 1.0*MDH_2 - 1.0*MDH_2_reverse_a8b90 - 4.0*NADH16_2 + 4.0*NADH16_2_reverse_7dfde + 1.0*PFK_2 - 1.0*PFK_2_reverse_ff38b + 1.0*PGL_2 - 1.0*PGL_2_reverse_c9bff + 1.0*PIt2r_2 - 1.0*PIt2r_2_reverse_8e1ad + 1.0*PPC_2 - 1.0*PPC_2_reverse_d78d7 + 2.0*PPS_2 - 2.0*PPS_2_reverse_2b10c - 1.0*PYK_2 + 1.0*PYK_2_reverse_c2760 + 1.0*PYRt2_2 - 1.0*PYRt2_2_reverse_b4d57 + 2.0*SUCCt2_2_2 - 2.0*SUCCt2_2_2_reverse_31c6a + 1.0*SUCCt3_2 - 1.0*SUCCt3_2_reverse_1ec02 + 2.0*THD2_2 - 2.0*THD2_2_reverse_ac122
-1.0*ACt2r_2 + 1.0*ACt2r_2_reverse_e4a0f - 1.0*AKGt2r_2 + 1.0*AKGt2r_2_reverse_4d4f0 - 4.0*ATPS4r_2 + 4.0*ATPS4r_2_reverse_4b447 + 2.0*CYTBD_2 - 2.0*CYTBD_2_reverse_66ef2 - 1.0*D_LACt2_2 + 1.0*D_LACt2_2_reverse_a8152 - 1.0*ETOHt2r_2 + 1.0*ETOHt2r_2_reverse_8fe11 - 1.0*EX_h_e_2 + 1.0*EX_h_e_2_reverse_7e53f - 1.0*FORt2_2 + 1.0*FORt2_2_reverse_db98f - 2.0*FUMt2_2_2 + 2.0*FUMt2_2_2_reverse_98895 - 1.0*GLUt2r_2 + 1.0*GLUt2r_2_reverse_a1cdc - 2.0*MALt2_2_2 + 2.0*MALt2_2_2_reverse_71b7e + 3.0*NADH16_2 - 3.0*NADH16_2_reverse_7dfde - 1.0*PIt2r_2 + 1.0*PIt2r_2_reverse_8e1ad - 1.0*PYRt2_2 + 1.0*PYRt2_2_reverse_b4d57 - 2.0*SUCCt2_2_2 + 2.0*SUCCt2_2_2_reverse_31c6a - 1.0*SUCCt3_2 + 1.0*SUCCt3_2_reverse_1ec02 - 2.0*THD2_2 + 2.0*THD2_2_reverse_ac122
1.0*ACONTb_2 - 1.0*ACONTb_2_reverse_0eaf5 - 1.0*ICDHyr_2 + 1.0*ICDHyr_2_reverse_799d2 - 1.0*ICL_2 + 1.0*ICL_2_reverse_5b4ec
1.0*D_LACt2_2 - 1.0*D_LACt2_2_reverse_a8152 - 1.0*LDH_D_2 + 1.0*LDH_D_2_reverse_daca6
-1.0*D_LACt2_2 + 1.0*D_LACt2_2_reverse_a8152 - 1.0*EX_lac__D_e_2 + 1.0*EX_lac__D_e_2_reverse_dc816
1.0*FUM_2 - 1.0*FUM_2_reverse_83caf + 1.0*MALS_2 - 1.0*MALS_2_reverse_e76be + 1.0*MALt2_2_2 - 1.0*MALt2_2_2_reverse_71b7e - 1.0*MDH_2 + 1.0*MDH_2_reverse_a8b90 - 1.0*ME1_2 + 1.0*ME1_2_reverse_63695 - 1.0*ME2_2 + 1.0*ME2_2_reverse_b92af
-1.0*EX_mal__L_e_2 + 1.0*EX_mal__L_e_2_reverse_ce541 - 1.0*MALt2_2_2 + 1.0*MALt2_2_2_reverse_71b7e
-1.0*ACALD_2 + 1.0*ACALD_2_reverse_e1a2f - 1.0*AKGDH_2 + 1.0*AKGDH_2_reverse_7ed30 - 1.0*ALCD2x_2 + 1.0*ALCD2x_2_reverse_809dd - 3.547*Biomass_Ecoli_core_2 + 3.547*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*GAPD_2 + 1.0*GAPD_2_reverse_ee85f - 1.0*LDH_D_2 + 1.0*LDH_D_2_reverse_daca6 - 1.0*MDH_2 + 1.0*MDH_2_reverse_a8b90 - 1.0*ME1_2 + 1.0*ME1_2_reverse_63695 + 1.0*NADH16_2 - 1.0*NADH16_2_reverse_7dfde - 1.0*NADTRHD_2 + 1.0*NADTRHD_2_reverse_f01a0 - 1.0*PDH_2 + 1.0*PDH_2_reverse_ca386 + 1.0*THD2_2 - 1.0*THD2_2_reverse_ac122
1.0*ACALD_2 - 1.0*ACALD_2_reverse_e1a2f + 1.0*AKGDH_2 - 1.0*AKGDH_2_reverse_7ed30 + 1.0*ALCD2x_2 - 1.0*ALCD2x_2_reverse_809dd + 3.547*Biomass_Ecoli_core_2 - 3.547*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*GAPD_2 - 1.0*GAPD_2_reverse_ee85f + 1.0*LDH_D_2 - 1.0*LDH_D_2_reverse_daca6 + 1.0*MDH_2 - 1.0*MDH_2_reverse_a8b90 + 1.0*ME1_2 - 1.0*ME1_2_reverse_63695 - 1.0*NADH16_2 + 1.0*NADH16_2_reverse_7dfde + 1.0*NADTRHD_2 - 1.0*NADTRHD_2_reverse_f01a0 + 1.0*PDH_2 - 1.0*PDH_2_reverse_ca386 - 1.0*THD2_2 + 1.0*THD2_2_reverse_ac122
13.0279*Biomass_Ecoli_core_2 - 13.0279*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*G6PDH2r_2 + 1.0*G6PDH2r_2_reverse_29261 - 1.0*GLUDy_2 + 1.0*GLUDy_2_reverse_5f7c0 + 1.0*GLUSy_2 - 1.0*GLUSy_2_reverse_8b8ce - 1.0*GND_2 + 1.0*GND_2_reverse_13977 - 1.0*ICDHyr_2 + 1.0*ICDHyr_2_reverse_799d2 - 1.0*ME2_2 + 1.0*ME2_2_reverse_b92af + 1.0*NADTRHD_2 - 1.0*NADTRHD_2_reverse_f01a0 - 1.0*THD2_2 + 1.0*THD2_2_reverse_ac122
-13.0279*Biomass_Ecoli_core_2 + 13.0279*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*G6PDH2r_2 - 1.0*G6PDH2r_2_reverse_29261 + 1.0*GLUDy_2 - 1.0*GLUDy_2_reverse_5f7c0 - 1.0*GLUSy_2 + 1.0*GLUSy_2_reverse_8b8ce + 1.0*GND_2 - 1.0*GND_2_reverse_13977 + 1.0*ICDHyr_2 - 1.0*ICDHyr_2_reverse_799d2 + 1.0*ME2_2 - 1.0*ME2_2_reverse_b92af - 1.0*NADTRHD_2 + 1.0*NADTRHD_2_reverse_f01a0 + 1.0*THD2_2 - 1.0*THD2_2_reverse_ac122
-1.0*GLNS_2 + 1.0*GLNS_2_reverse_5559c + 1.0*GLUDy_2 - 1.0*GLUDy_2_reverse_5f7c0 + 1.0*GLUN_2 - 1.0*GLUN_2_reverse_1f598 + 1.0*NH4t_2 - 1.0*NH4t_2_reverse_b69d1
-1.0*EX_nh4_e_2 + 1.0*EX_nh4_e_2_reverse_8c7a1 - 1.0*NH4t_2 + 1.0*NH4t_2_reverse_b69d1
-0.5*CYTBD_2 + 0.5*CYTBD_2_reverse_66ef2 + 1.0*O2t_2 - 1.0*O2t_2_reverse_b7a86
-1.0*EX_o2_e_2 + 1.0*EX_o2_e_2_reverse_796b8 - 1.0*O2t_2 + 1.0*O2t_2_reverse_b7a86
-1.7867*Biomass_Ecoli_core_2 + 1.7867*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*CS_2 + 1.0*CS_2_reverse_d9dba + 1.0*MDH_2 - 1.0*MDH_2_reverse_a8b90 - 1.0*PPCK_2 + 1.0*PPCK_2_reverse_6323d + 1.0*PPC_2 - 1.0*PPC_2_reverse_d78d7
-0.5191*Biomass_Ecoli_core_2 + 0.5191*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*ENO_2 - 1.0*ENO_2_reverse_504d6 - 1.0*FRUpts2_2 + 1.0*FRUpts2_2_reverse_8a962 - 1.0*GLCpts_2 + 1.0*GLCpts_2_reverse_bbdcb + 1.0*PPCK_2 - 1.0*PPCK_2_reverse_6323d - 1.0*PPC_2 + 1.0*PPC_2_reverse_d78d7 + 1.0*PPS_2 - 1.0*PPS_2_reverse_2b10c - 1.0*PYK_2 + 1.0*PYK_2_reverse_c2760
1.0*ATPM_2 - 1.0*ATPM_2_reverse_e9efb - 1.0*ATPS4r_2 + 1.0*ATPS4r_2_reverse_4b447 + 59.81*Biomass_Ecoli_core_2 - 59.81*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*FBP_2 - 1.0*FBP_2_reverse_40e3f - 1.0*GAPD_2 + 1.0*GAPD_2_reverse_ee85f + 1.0*GLNS_2 - 1.0*GLNS_2_reverse_5559c + 1.0*GLNabc_2 - 1.0*GLNabc_2_reverse_c912b + 1.0*PIt2r_2 - 1.0*PIt2r_2_reverse_8e1ad + 1.0*PPC_2 - 1.0*PPC_2_reverse_d78d7 + 1.0*PPS_2 - 1.0*PPS_2_reverse_2b10c - 1.0*PTAr_2 + 1.0*PTAr_2_reverse_39042 + 1.0*SUCOAS_2 - 1.0*SUCOAS_2_reverse_15f9c
-1.0*EX_pi_e_2 + 1.0*EX_pi_e_2_reverse_55ec1 - 1.0*PIt2r_2 + 1.0*PIt2r_2_reverse_8e1ad
-2.8328*Biomass_Ecoli_core_2 + 2.8328*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*FRUpts2_2 - 1.0*FRUpts2_2_reverse_8a962 + 1.0*GLCpts_2 - 1.0*GLCpts_2_reverse_bbdcb + 1.0*LDH_D_2 - 1.0*LDH_D_2_reverse_daca6 + 1.0*ME1_2 - 1.0*ME1_2_reverse_63695 + 1.0*ME2_2 - 1.0*ME2_2_reverse_b92af - 1.0*PDH_2 + 1.0*PDH_2_reverse_ca386 - 1.0*PFL_2 + 1.0*PFL_2_reverse_eed7a - 1.0*PPS_2 + 1.0*PPS_2_reverse_2b10c + 1.0*PYK_2 - 1.0*PYK_2_reverse_c2760 + 1.0*PYRt2_2 - 1.0*PYRt2_2_reverse_b4d57
-1.0*EX_pyr_e_2 + 1.0*EX_pyr_e_2_reverse_e8775 - 1.0*PYRt2_2 + 1.0*PYRt2_2_reverse_b4d57
1.0*CYTBD_2 - 1.0*CYTBD_2_reverse_66ef2 + 1.0*FRD7_2 - 1.0*FRD7_2_reverse_73a9f - 1.0*NADH16_2 + 1.0*NADH16_2_reverse_7dfde - 1.0*SUCDi_2 + 1.0*SUCDi_2_reverse_10183
-1.0*CYTBD_2 + 1.0*CYTBD_2_reverse_66ef2 - 1.0*FRD7_2 + 1.0*FRD7_2_reverse_73a9f + 1.0*NADH16_2 - 1.0*NADH16_2_reverse_7dfde + 1.0*SUCDi_2 - 1.0*SUCDi_2_reverse_10183
-0.8977*Biomass_Ecoli_core_2 + 0.8977*Biomass_Ecoli_core_2_reverse_a6524 - 1.0*RPI_2 + 1.0*RPI_2_reverse_ddf0e - 1.0*TKT1_2 + 1.0*TKT1_2_reverse_f68af
1.0*GND_2 - 1.0*GND_2_reverse_13977 - 1.0*RPE_2 + 1.0*RPE_2_reverse_0dd8d + 1.0*RPI_2 - 1.0*RPI_2_reverse_ddf0e
-1.0*TALA_2 + 1.0*TALA_2_reverse_a07de + 1.0*TKT1_2 - 1.0*TKT1_2_reverse_f68af
1.0*FRD7_2 - 1.0*FRD7_2_reverse_73a9f + 1.0*ICL_2 - 1.0*ICL_2_reverse_5b4ec + 1.0*SUCCt2_2_2 - 1.0*SUCCt2_2_2_reverse_31c6a - 1.0*SUCCt3_2 + 1.0*SUCCt3_2_reverse_1ec02 - 1.0*SUCDi_2 + 1.0*SUCDi_2_reverse_10183 - 1.0*SUCOAS_2 + 1.0*SUCOAS_2_reverse_15f9c
-1.0*EX_succ_e_2 + 1.0*EX_succ_e_2_reverse_cb0fc - 1.0*SUCCt2_2_2 + 1.0*SUCCt2_2_2_reverse_31c6a + 1.0*SUCCt3_2 - 1.0*SUCCt3_2_reverse_1ec02
1.0*AKGDH_2 - 1.0*AKGDH_2_reverse_7ed30 + 1.0*SUCOAS_2 - 1.0*SUCOAS_2_reverse_15f9c
1.0*RPE_2 - 1.0*RPE_2_reverse_0dd8d - 1.0*TKT1_2 + 1.0*TKT1_2_reverse_f68af - 1.0*TKT2_2 + 1.0*TKT2_2_reverse_62491
1.0*ACALD_2 + 1.0*ACALD_2_reverse_e1a2f + 1.0*ACALDt_2 + 1.0*ACALDt_2_reverse_56955 + 1.0*ACKr_2 + 1.0*ACKr_2_reverse_1d125 + 1.0*ACONTa_2 + 1.0*ACONTa_2_reverse_b464e + 1.0*ACONTb_2 + 1.0*ACONTb_2_reverse_0eaf5 + 1.0*ACt2r_2 + 1.0*ACt2r_2_reverse_e4a0f + 1.0*ADK1_2 + 1.0*ADK1_2_reverse_1f1fe + 1.0*AKGDH_2 + 1.0*AKGDH_2_reverse_7ed30 + 1.0*AKGt2r_2 + 1.0*AKGt2r_2_reverse_4d4f0 + 1.0*ALCD2x_2 + 1.0*ALCD2x_2_reverse_809dd + 1.0*ATPM_2 + 1.0*ATPM_2_reverse_e9efb + 1.0*ATPS4r_2 + 1.0*ATPS4r_2_reverse_4b447 + 1.0*Biomass_Ecoli_core_2 + 1.0*Biomass_Ecoli_core_2_reverse_a6524 + 1.0*CO2t_2 + 1.0*CO2t_2_reverse_9d99f + 1.0*CS_2 + 1.0*CS_2_reverse_d9dba + 1.0*CYTBD_2 + 1.0*CYTBD_2_reverse_66ef2 + 1.0*D_LACt2_2 + 1.0*D_LACt2_2_reverse_a8152 + 1.0*ENO_2 + 1.0*ENO_2_reverse_504d6 + 1.0*ETOHt2r_2 + 1.0*ETOHt2r_2_reverse_8fe11 + 1.0*EX_ac_e_2 + 1.0*EX_ac_e_2_reverse_5d7e5 + 1.0*EX_acald_e_2 + 1.0*EX_acald_e_2_reverse_7bc8d + 1.0*EX_akg_e_2 + 1.0*EX_akg_e_2_reverse_b1d5e + 1.0*EX_co2_e_2 + 1.0*EX_co2_e_2_reverse_3c0c0 + 1.0*EX_etoh_e_2 + 1.0*EX_etoh_e_2_reverse_b40bf + 1.0*EX_for_e_2 + 1.0*EX_for_e_2_reverse_6f6c8 + 1.0*EX_fru_e_2 + 1.0*EX_fru_e_2_reverse_71238 + 1.0*EX_fum_e_2 + 1.0*EX_fum_e_2_reverse_e23c1 + 1.0*EX_glc__D_e_2 + 1.0*EX_glc__D_e_2_reverse_f4e76 + 1.0*EX_gln__L_e_2 + 1.0*EX_gln__L_e_2_reverse_e5e6c + 1.0*EX_glu__L_e_2 + 1.0*EX_glu__L_e_2_reverse_9b53d + 1.0*EX_h2o_e_2 + 1.0*EX_h2o_e_2_reverse_b38e5 + 1.0*EX_h_e_2 + 1.0*EX_h_e_2_reverse_7e53f + 1.0*EX_lac__D_e_2 + 1.0*EX_lac__D_e_2_reverse_dc816 + 1.0*EX_mal__L_e_2 + 1.0*EX_mal__L_e_2_reverse_ce541 + 1.0*EX_nh4_e_2 + 1.0*EX_nh4_e_2_reverse_8c7a1 + 1.0*EX_o2_e_2 + 1.0*EX_o2_e_2_reverse_796b8 + 1.0*EX_pi_e_2 + 1.0*EX_pi_e_2_reverse_55ec1 + 1.0*EX_pyr_e_2 + 1.0*EX_pyr_e_2_reverse_e8775 + 1.0*EX_succ_e_2 + 1.0*EX_succ_e_2_reverse_cb0fc + 1.0*FBA_2 + 1.0*FBA_2_reverse_bcfcc + 1.0*FBP_2 + 1.0*FBP_2_reverse_40e3f + 1.0*FORt2_2 + 1.0*FORt2_2_reverse_db98f + 1.0*FORti_2 + 1.0*FORti_2_reverse_ef2d5 + 1.0*FRD7_2 + 1.0*FRD7_2_reverse_73a9f + 1.0*FRUpts2_2 + 1.0*FRUpts2_2_reverse_8a962 + 1.0*FUM_2 + 1.0*FUM_2_reverse_83caf + 1.0*FUMt2_2_2 + 1.0*FUMt2_2_2_reverse_98895 + 1.0*G6PDH2r_2 + 1.0*G6PDH2r_2_reverse_29261 + 1.0*GAPD_2 + 1.0*GAPD_2_reverse_ee85f + 1.0*GLCpts_2 + 1.0*GLCpts_2_reverse_bbdcb + 1.0*GLNS_2 + 1.0*GLNS_2_reverse_5559c + 1.0*GLNabc_2 + 1.0*GLNabc_2_reverse_c912b + 1.0*GLUDy_2 + 1.0*GLUDy_2_reverse_5f7c0 + 1.0*GLUN_2 + 1.0*GLUN_2_reverse_1f598 + 1.0*GLUSy_2 + 1.0*GLUSy_2_reverse_8b8ce + 1.0*GLUt2r_2 + 1.0*GLUt2r_2_reverse_a1cdc + 1.0*GND_2 + 1.0*GND_2_reverse_13977 + 1.0*H2Ot_2 + 1.0*H2Ot_2_reverse_1a867 + 1.0*ICDHyr_2 + 1.0*ICDHyr_2_reverse_799d2 + 1.0*ICL_2 + 1.0*ICL_2_reverse_5b4ec + 1.0*LDH_D_2 + 1.0*LDH_D_2_reverse_daca6 + 1.0*MALS_2 + 1.0*MALS_2_reverse_e76be + 1.0*MALt2_2_2 + 1.0*MALt2_2_2_reverse_71b7e + 1.0*MDH_2 + 1.0*MDH_2_reverse_a8b90 + 1.0*ME1_2 + 1.0*ME1_2_reverse_63695 + 1.0*ME2_2 + 1.0*ME2_2_reverse_b92af + 1.0*NADH16_2 + 1.0*NADH16_2_reverse_7dfde + 1.0*NADTRHD_2 + 1.0*NADTRHD_2_reverse_f01a0 + 1.0*NH4t_2 + 1.0*NH4t_2_reverse_b69d1 + 1.0*O2t_2 + 1.0*O2t_2_reverse_b7a86 + 1.0*PDH_2 + 1.0*PDH_2_reverse_ca386 + 1.0*PFK_2 + 1.0*PFK_2_reverse_ff38b + 1.0*PFL_2 + 1.0*PFL_2_reverse_eed7a + 1.0*PGI_2 + 1.0*PGI_2_reverse_3f620 + 1.0*PGK_2 + 1.0*PGK_2_reverse_f19c0 + 1.0*PGL_2 + 1.0*PGL_2_reverse_c9bff + 1.0*PGM_2 + 1.0*PGM_2_reverse_245dd + 1.0*PIt2r_2 + 1.0*PIt2r_2_reverse_8e1ad + 1.0*PPCK_2 + 1.0*PPCK_2_reverse_6323d + 1.0*PPC_2 + 1.0*PPC_2_reverse_d78d7 + 1.0*PPS_2 + 1.0*PPS_2_reverse_2b10c + 1.0*PTAr_2 + 1.0*PTAr_2_reverse_39042 + 1.0*PYK_2 + 1.0*PYK_2_reverse_c2760 + 1.0*PYRt2_2 + 1.0*PYRt2_2_reverse_b4d57 + 1.0*RPE_2 + 1.0*RPE_2_reverse_0dd8d + 1.0*RPI_2 + 1.0*RPI_2_reverse_ddf0e + 1.0*SUCCt2_2_2 + 1.0*SUCCt2_2_2_reverse_31c6a + 1.0*SUCCt3_2 + 1.0*SUCCt3_2_reverse_1ec02 + 1.0*SUCDi_2 + 1.0*SUCDi_2_reverse_10183 + 1.0*SUCOAS_2 + 1.0*SUCOAS_2_reverse_15f9c + 1.0*TALA_2 + 1.0*TALA_2_reverse_a07de + 1.0*THD2_2 + 1.0*THD2_2_reverse_ac122 + 1.0*TKT1_2 + 1.0*TKT1_2_reverse_f68af + 1.0*TKT2_2 + 1.0*TKT2_2_reverse_62491 + 1.0*TPI_2 + 1.0*TPI_2_reverse_ccea1

In [55]:
sum([i.primal for i in model.solver.variables.values()])

518.4220855176067

In [60]:
[i for i in model.solver.variables.values()]

[0 <= ACALD <= 1000.0,
 0 <= ACALD_reverse_fda2b <= 1000.0,
 0 <= ACALDt <= 1000.0,
 0 <= ACALDt_reverse_858fa <= 1000.0,
 0 <= ACKr <= 1000.0,
 0 <= ACKr_reverse_b49c0 <= 1000.0,
 0 <= ACONTa <= 1000.0,
 0 <= ACONTa_reverse_cad6d <= 1000.0,
 0 <= ACONTb <= 1000.0,
 0 <= ACONTb_reverse_e198a <= 1000.0,
 0 <= ACt2r <= 1000.0,
 0 <= ACt2r_reverse_64e05 <= 1000.0,
 0 <= ADK1 <= 1000.0,
 0 <= ADK1_reverse_a6f90 <= 1000.0,
 0 <= AKGDH <= 1000.0,
 0 <= AKGDH_reverse_08bdc <= -0.0,
 0 <= AKGt2r <= 1000.0,
 0 <= AKGt2r_reverse_5d500 <= 1000.0,
 0 <= ALCD2x <= 1000.0,
 0 <= ALCD2x_reverse_5d107 <= 1000.0,
 8.39 <= ATPM <= 1000.0,
 0 <= ATPM_reverse_5b752 <= 0,
 0 <= ATPS4r <= 1000.0,
 0 <= ATPS4r_reverse_64306 <= 1000.0,
 0 <= Biomass_Ecoli_core <= 1000.0,
 0 <= Biomass_Ecoli_core_reverse_2cdba <= -0.0,
 0 <= CO2t <= 1000.0,
 0 <= CO2t_reverse_7c42f <= 1000.0,
 0 <= CS <= 1000.0,
 0 <= CS_reverse_8d7e9 <= -0.0,
 0 <= CYTBD <= 1000.0,
 0 <= CYTBD_reverse_611ba <= -0.0,
 0 <= D_LACt2 <= 1000.0,
 0 <= D_LACt2_reverse_d0dc8 <= 1000.0,
 0 <= ENO <= 1000.0,
 0 <= ENO_reverse_40eea <= 1000.0,
 0 <= ETOHt2r <= 1000.0,
 0 <= ETOHt2r_reverse_b3d52 <= 1000.0,
 0 <= EX_ac_e <= 1000.0,
 0 <= EX_ac_e_reverse_0be96 <= -0.0,
 0 <= EX_acald_e <= 1000.0,
 0 <= EX_acald_e_reverse_c096e <= -0.0,
 0 <= EX_akg_e <= 1000.0,
 0 <= EX_akg_e_reverse_70d85 <= -0.0,
 0 <= EX_co2_e <= 1000.0,
 0 <= EX_co2_e_reverse_d0466 <= 1000.0,
 0 <= EX_etoh_e <= 1000.0,
 0 <= EX_etoh_e_reverse_cc64f <= -0.0,
 0 <= EX_for_e <= 1000.0,
 0 <= EX_for_e_reverse_23269 <= -0.0,
 0 <= EX_fru_e <= 1000.0,
 0 <= EX_fru_e_reverse_c3828 <= -0.0,
 0 <= EX_fum_e <= 1000.0,
 0 <= EX_fum_e_reverse_e3432 <= -0.0,
 0 <= EX_glc__D_e <= 1000.0,
 0 <= EX_glc__D_e_reverse_af641 <= 10.0,
 0 <= EX_gln__L_e <= 1000.0,
 0 <= EX_gln__L_e_reverse_6a1a1 <= -0.0,
 0 <= EX_glu__L_e <= 1000.0,
 0 <= EX_glu__L_e_reverse_42f6c <= -0.0,
 0 <= EX_h_e <= 1000.0,
 0 <= EX_h_e_reverse_3e0c5 <= 1000.0,
 0 <= EX_h2o_e <= 1000.0,
 0 <= EX_h2o_e_reverse_3ced4 <= 1000.0,
 0 <= EX_lac__D_e <= 1000.0,
 0 <= EX_lac__D_e_reverse_f95b4 <= -0.0,
 0 <= EX_mal__L_e <= 1000.0,
 0 <= EX_mal__L_e_reverse_af154 <= -0.0,
 0 <= EX_nh4_e <= 1000.0,
 0 <= EX_nh4_e_reverse_f9cc6 <= 1000.0,
 0 <= EX_o2_e <= 1000.0,
 0 <= EX_o2_e_reverse_efa94 <= 1000.0,
 0 <= EX_pi_e <= 1000.0,
 0 <= EX_pi_e_reverse_1fb09 <= 1000.0,
 0 <= EX_pyr_e <= 1000.0,
 0 <= EX_pyr_e_reverse_1f6de <= -0.0,
 0 <= EX_succ_e <= 1000.0,
 0 <= EX_succ_e_reverse_a9039 <= -0.0,
 0 <= FBA <= 1000.0,
 0 <= FBA_reverse_84806 <= 1000.0,
 0 <= FBP <= 1000.0,
 0 <= FBP_reverse_bf2c9 <= -0.0,
 0 <= FORt2 <= 1000.0,
 0 <= FORt2_reverse_89839 <= -0.0,
 0 <= FORti <= 1000.0,
 0 <= FORti_reverse_18c06 <= -0.0,
 0 <= FRD7 <= 1000.0,
 0 <= FRD7_reverse_e0172 <= -0.0,
 0 <= FRUpts2 <= 1000.0,
 0 <= FRUpts2_reverse_58d3a <= -0.0,
 0 <= FUM <= 1000.0,
 0 <= FUM_reverse_d3642 <= 1000.0,
 0 <= FUMt2_2 <= 1000.0,
 0 <= FUMt2_2_reverse_7b4b6 <= -0.0,
 0 <= G6PDH2r <= 1000.0,
 0 <= G6PDH2r_reverse_19ddf <= 1000.0,
 0 <= GAPD <= 1000.0,
 0 <= GAPD_reverse_459c1 <= 1000.0,
 0 <= GLCpts <= 1000.0,
 0 <= GLCpts_reverse_a52ae <= -0.0,
 0 <= GLNS <= 1000.0,
 0 <= GLNS_reverse_59581 <= -0.0,
 0 <= GLNabc <= 1000.0,
 0 <= GLNabc_reverse_1d82a <= -0.0,
 0 <= GLUDy <= 1000.0,
 0 <= GLUDy_reverse_fa4e7 <= 1000.0,
 0 <= GLUN <= 1000.0,
 0 <= GLUN_reverse_4ccdb <= -0.0,
 0 <= GLUSy <= 1000.0,
 0 <= GLUSy_reverse_6a00f <= -0.0,
 0 <= GLUt2r <= 1000.0,
 0 <= GLUt2r_reverse_3e88a <= 1000.0,
 0 <= GND <= 1000.0,
 0 <= GND_reverse_eec5c <= -0.0,
 0 <= H2Ot <= 1000.0,
 0 <= H2Ot_reverse_aa560 <= 1000.0,
 0 <= ICDHyr <= 1000.0,
 0 <= ICDHyr_reverse_7f84b <= 1000.0,
 0 <= ICL <= 1000.0,
 0 <= ICL_reverse_2f27e <= -0.0,
 0 <= LDH_D <= 1000.0,
 0 <= LDH_D_reverse_f8507 <= 1000.0,
 0 <= MALS <= 1000.0,
 0 <= MALS_reverse_d7382 <= -0.0,
 0 <= MALt2_2 <= 1000.0,
 0 <= MALt2_2_reverse_a635f <= -0.0,
 0 <= MDH <= 1000.0,
 0 <= MDH_reverse_ee52c <= 1000.0,
 0 <= ME1 <= 1000.0,
 0 <= ME1_reverse_9736c <= -0.0,
 0 <= ME2 <= 1000.0,
 0 <= ME2_reverse_2b0a2 <= -0.0,
 0 <= NADH16 <= 1000.0,
 0 <= NADH16_reverse_330a2 <= -0.0,
 0 <= NADTRHD <= 1000.0,
 0 <= NADTRHD_reverse_49725 <= -0.0,
 0 <= NH4t <= 1000.0,
 0 <= NH4t_reverse_551ee <= 1000.0,
 0 <= O2t <= 1000.0,
 0 <= O2t_reverse_4d957 <= 1000.0,
 0 <= PDH <= 1000.0,
 0 <= PDH_reverse_ca160 <= -0.0,
 0 <= PFK <= 1000.0,
 0 <= PFK_reverse_d24a6 <= -0.0,
 0 <= PFL <= 1000.0,
 0 <= PFL_reverse_af9ec <= -0.0,
 0 <= PGI <= 1000.0,
 0 <= PGI_reverse_27efc <= 1000.0,
 0 <= PGK <= 1000.0,
 0 <= PGK_reverse_02696 <= 1000.0,
 0 <= PGL <= 1000.0,
 0 <= PGL_reverse_2bb6b <= -0.0,
 0 <= PGM <= 1000.0,
 0 <= PGM_reverse_fc9af <= 1000.0,
 0 <= PIt2r <= 1000.0,
 0 <= PIt2r_reverse_1cd61 <= 1000.0,
 0 <= PPC <= 1000.0,
 0 <= PPC_reverse_e854a <= -0.0,
 0 <= PPCK <= 1000.0,
 0 <= PPCK_reverse_2557d <= -0.0,
 0 <= PPS <= 1000.0,
 0 <= PPS_reverse_1c319 <= -0.0,
 0 <= PTAr <= 1000.0,
 0 <= PTAr_reverse_fce15 <= 1000.0,
 0 <= PYK <= 1000.0,
 0 <= PYK_reverse_bc8ff <= -0.0,
 0 <= PYRt2 <= 1000.0,
 0 <= PYRt2_reverse_a6e24 <= 1000.0,
 0 <= RPE <= 1000.0,
 0 <= RPE_reverse_a1b04 <= 1000.0,
 0 <= RPI <= 1000.0,
 0 <= RPI_reverse_853a1 <= 1000.0,
 0 <= SUCCt2_2 <= 1000.0,
 0 <= SUCCt2_2_reverse_206ca <= -0.0,
 0 <= SUCCt3 <= 1000.0,
 0 <= SUCCt3_reverse_7d82a <= -0.0,
 0 <= SUCDi <= 1000.0,
 0 <= SUCDi_reverse_480f4 <= -0.0,
 0 <= SUCOAS <= 1000.0,
 0 <= SUCOAS_reverse_22958 <= 1000.0,
 0 <= TALA <= 1000.0,
 0 <= TALA_reverse_adfda <= 1000.0,
 0 <= THD2 <= 1000.0,
 0 <= THD2_reverse_f65dd <= -0.0,
 0 <= TKT1 <= 1000.0,
 0 <= TKT1_reverse_a1021 <= 1000.0,
 0 <= TKT2 <= 1000.0,
 0 <= TKT2_reverse_7ebc7 <= 1000.0,
 0 <= TPI <= 1000.0,
 0 <= TPI_reverse_c2c3b <= 1000.0]

In [48]:
constraint.variables

{0 <= ACALD <= 1000.0,
 0 <= ACALD_reverse_fda2b <= 1000.0,
 0 <= ACALDt <= 1000.0,
 0 <= ACALDt_reverse_858fa <= 1000.0,
 0 <= ACKr <= 1000.0,
 0 <= ACKr_reverse_b49c0 <= 1000.0,
 0 <= ACONTa <= 1000.0,
 0 <= ACONTa_reverse_cad6d <= 1000.0,
 0 <= ACONTb <= 1000.0,
 0 <= ACONTb_reverse_e198a <= 1000.0,
 0 <= ACt2r <= 1000.0,
 0 <= ACt2r_reverse_64e05 <= 1000.0,
 0 <= ADK1 <= 1000.0,
 0 <= ADK1_reverse_a6f90 <= 1000.0,
 0 <= AKGDH <= 1000.0,
 0 <= AKGDH_reverse_08bdc <= -0.0,
 0 <= AKGt2r <= 1000.0,
 0 <= AKGt2r_reverse_5d500 <= 1000.0,
 0 <= ALCD2x <= 1000.0,
 0 <= ALCD2x_reverse_5d107 <= 1000.0,
 0 <= ATPM_reverse_5b752 <= 0,
 0 <= ATPS4r <= 1000.0,
 0 <= ATPS4r_reverse_64306 <= 1000.0,
 0 <= Biomass_Ecoli_core <= 1000.0,
 0 <= Biomass_Ecoli_core_reverse_2cdba <= -0.0,
 0 <= CO2t <= 1000.0,
 0 <= CO2t_reverse_7c42f <= 1000.0,
 0 <= CS <= 1000.0,
 0 <= CS_reverse_8d7e9 <= -0.0,
 0 <= CYTBD <= 1000.0,
 0 <= CYTBD_reverse_611ba <= -0.0,
 0 <= D_LACt2 <= 1000.0,
 0 <= D_LACt2_reverse_d0dc8 <= 1000.0,
 0 <= ENO <= 1000.0,
 0 <= ENO_reverse_40eea <= 1000.0,
 0 <= ETOHt2r <= 1000.0,
 0 <= ETOHt2r_reverse_b3d52 <= 1000.0,
 0 <= EX_ac_e <= 1000.0,
 0 <= EX_ac_e_reverse_0be96 <= -0.0,
 0 <= EX_acald_e <= 1000.0,
 0 <= EX_acald_e_reverse_c096e <= -0.0,
 0 <= EX_akg_e <= 1000.0,
 0 <= EX_akg_e_reverse_70d85 <= -0.0,
 0 <= EX_co2_e <= 1000.0,
 0 <= EX_co2_e_reverse_d0466 <= 1000.0,
 0 <= EX_etoh_e <= 1000.0,
 0 <= EX_etoh_e_reverse_cc64f <= -0.0,
 0 <= EX_for_e <= 1000.0,
 0 <= EX_for_e_reverse_23269 <= -0.0,
 0 <= EX_fru_e <= 1000.0,
 0 <= EX_fru_e_reverse_c3828 <= -0.0,
 0 <= EX_fum_e <= 1000.0,
 0 <= EX_fum_e_reverse_e3432 <= -0.0,
 0 <= EX_glc__D_e <= 1000.0,
 0 <= EX_glc__D_e_reverse_af641 <= 10.0,
 0 <= EX_gln__L_e <= 1000.0,
 0 <= EX_gln__L_e_reverse_6a1a1 <= -0.0,
 0 <= EX_glu__L_e <= 1000.0,
 0 <= EX_glu__L_e_reverse_42f6c <= -0.0,
 0 <= EX_h2o_e <= 1000.0,
 0 <= EX_h2o_e_reverse_3ced4 <= 1000.0,
 0 <= EX_h_e <= 1000.0,
 0 <= EX_h_e_reverse_3e0c5 <= 1000.0,
 0 <= EX_lac__D_e <= 1000.0,
 0 <= EX_lac__D_e_reverse_f95b4 <= -0.0,
 0 <= EX_mal__L_e <= 1000.0,
 0 <= EX_mal__L_e_reverse_af154 <= -0.0,
 0 <= EX_nh4_e <= 1000.0,
 0 <= EX_nh4_e_reverse_f9cc6 <= 1000.0,
 0 <= EX_o2_e <= 1000.0,
 0 <= EX_o2_e_reverse_efa94 <= 1000.0,
 0 <= EX_pi_e <= 1000.0,
 0 <= EX_pi_e_reverse_1fb09 <= 1000.0,
 0 <= EX_pyr_e <= 1000.0,
 0 <= EX_pyr_e_reverse_1f6de <= -0.0,
 0 <= EX_succ_e <= 1000.0,
 0 <= EX_succ_e_reverse_a9039 <= -0.0,
 0 <= FBA <= 1000.0,
 0 <= FBA_reverse_84806 <= 1000.0,
 0 <= FBP <= 1000.0,
 0 <= FBP_reverse_bf2c9 <= -0.0,
 0 <= FORt2 <= 1000.0,
 0 <= FORt2_reverse_89839 <= -0.0,
 0 <= FORti <= 1000.0,
 0 <= FORti_reverse_18c06 <= -0.0,
 0 <= FRD7 <= 1000.0,
 0 <= FRD7_reverse_e0172 <= -0.0,
 0 <= FRUpts2 <= 1000.0,
 0 <= FRUpts2_reverse_58d3a <= -0.0,
 0 <= FUM <= 1000.0,
 0 <= FUM_reverse_d3642 <= 1000.0,
 0 <= FUMt2_2 <= 1000.0,
 0 <= FUMt2_2_reverse_7b4b6 <= -0.0,
 0 <= G6PDH2r <= 1000.0,
 0 <= G6PDH2r_reverse_19ddf <= 1000.0,
 0 <= GAPD <= 1000.0,
 0 <= GAPD_reverse_459c1 <= 1000.0,
 0 <= GLCpts <= 1000.0,
 0 <= GLCpts_reverse_a52ae <= -0.0,
 0 <= GLNS <= 1000.0,
 0 <= GLNS_reverse_59581 <= -0.0,
 0 <= GLNabc <= 1000.0,
 0 <= GLNabc_reverse_1d82a <= -0.0,
 0 <= GLUDy <= 1000.0,
 0 <= GLUDy_reverse_fa4e7 <= 1000.0,
 0 <= GLUN <= 1000.0,
 0 <= GLUN_reverse_4ccdb <= -0.0,
 0 <= GLUSy <= 1000.0,
 0 <= GLUSy_reverse_6a00f <= -0.0,
 0 <= GLUt2r <= 1000.0,
 0 <= GLUt2r_reverse_3e88a <= 1000.0,
 0 <= GND <= 1000.0,
 0 <= GND_reverse_eec5c <= -0.0,
 0 <= H2Ot <= 1000.0,
 0 <= H2Ot_reverse_aa560 <= 1000.0,
 0 <= ICDHyr <= 1000.0,
 0 <= ICDHyr_reverse_7f84b <= 1000.0,
 0 <= ICL <= 1000.0,
 0 <= ICL_reverse_2f27e <= -0.0,
 0 <= LDH_D <= 1000.0,
 0 <= LDH_D_reverse_f8507 <= 1000.0,
 0 <= MALS <= 1000.0,
 0 <= MALS_reverse_d7382 <= -0.0,
 0 <= MALt2_2 <= 1000.0,
 0 <= MALt2_2_reverse_a635f <= -0.0,
 0 <= MDH <= 1000.0,
 0 <= MDH_reverse_ee52c <= 1000.0,
 0 <= ME1 <= 1000.0,
 0 <= ME1_reverse_9736c <= -0.0,
 0 <= ME2 <= 1000.0,
 0 <= ME2_reverse_2b0a2 <= -0.0,
 0 <= NADH16 <= 1000.0,
 0 <= NADH16_reverse_330a2 <= -0.0,
 0 <= NADTRHD <= 1000.0,
 0 <= NADTRHD_reverse_49725 <= -0.0,
 0 <= NH4t <= 1000.0,
 0 <= NH4t_reverse_551ee <= 1000.0,
 0 <= O2t <= 1000.0,
 0 <= O2t_reverse_4d957 <= 1000.0,
 0 <= PDH <= 1000.0,
 0 <= PDH_reverse_ca160 <= -0.0,
 0 <= PFK <= 1000.0,
 0 <= PFK_reverse_d24a6 <= -0.0,
 0 <= PFL <= 1000.0,
 0 <= PFL_reverse_af9ec <= -0.0,
 0 <= PGI <= 1000.0,
 0 <= PGI_reverse_27efc <= 1000.0,
 0 <= PGK <= 1000.0,
 0 <= PGK_reverse_02696 <= 1000.0,
 0 <= PGL <= 1000.0,
 0 <= PGL_reverse_2bb6b <= -0.0,
 0 <= PGM <= 1000.0,
 0 <= PGM_reverse_fc9af <= 1000.0,
 0 <= PIt2r <= 1000.0,
 0 <= PIt2r_reverse_1cd61 <= 1000.0,
 0 <= PPC <= 1000.0,
 0 <= PPCK <= 1000.0,
 0 <= PPCK_reverse_2557d <= -0.0,
 0 <= PPC_reverse_e854a <= -0.0,
 0 <= PPS <= 1000.0,
 0 <= PPS_reverse_1c319 <= -0.0,
 0 <= PTAr <= 1000.0,
 0 <= PTAr_reverse_fce15 <= 1000.0,
 0 <= PYK <= 1000.0,
 0 <= PYK_reverse_bc8ff <= -0.0,
 0 <= PYRt2 <= 1000.0,
 0 <= PYRt2_reverse_a6e24 <= 1000.0,
 0 <= RPE <= 1000.0,
 0 <= RPE_reverse_a1b04 <= 1000.0,
 0 <= RPI <= 1000.0,
 0 <= RPI_reverse_853a1 <= 1000.0,
 0 <= SUCCt2_2 <= 1000.0,
 0 <= SUCCt2_2_reverse_206ca <= -0.0,
 0 <= SUCCt3 <= 1000.0,
 0 <= SUCCt3_reverse_7d82a <= -0.0,
 0 <= SUCDi <= 1000.0,
 0 <= SUCDi_reverse_480f4 <= -0.0,
 0 <= SUCOAS <= 1000.0,
 0 <= SUCOAS_reverse_22958 <= 1000.0,
 0 <= TALA <= 1000.0,
 0 <= TALA_reverse_adfda <= 1000.0,
 0 <= THD2 <= 1000.0,
 0 <= THD2_reverse_f65dd <= -0.0,
 0 <= TKT1 <= 1000.0,
 0 <= TKT1_reverse_a1021 <= 1000.0,
 0 <= TKT2 <= 1000.0,
 0 <= TKT2_reverse_7ebc7 <= 1000.0,
 0 <= TPI <= 1000.0,
 0 <= TPI_reverse_c2c3b <= 1000.0,
 8.39 <= ATPM <= 1000.0}

In [39]:
model.constraints['5907395b-e2e2-11ef-97bc-7cc2c624840e'].primal

100.0

In [40]:
model.constraints['tp'].primal

100.00000000000004

In [41]:
model.constraints['3850dc26-e2e4-11ef-9691-7cc2c624840e'].primal

100.00000000000004

In [38]:
solution = model.optimize()
print(solution)

<Solution 0.083 at 0x1dddefbcd30>

In [43]:
solution.fluxes.abs().sum()

99.99999999999997

In [20]:
model.variables

SyntaxError: invalid decimal literal (133913523.py, line 1)

In [19]:
for var in model.variables:
    print(f"{var.name}: {var.primal}")

ACALD: 0.0
ACALD_reverse_fda2b: 0.0
ACALDt: 0.0
ACALDt_reverse_858fa: 0.0
ACKr: 0.0
ACKr_reverse_b49c0: 2.491048778150239
ACONTa: 0.0898407178042207
ACONTa_reverse_cad6d: 0.0
ACONTb: 0.0898407178042207
ACONTb_reverse_e198a: 0.0
ACt2r: 0.0
ACt2r_reverse_64e05: 2.491048778150239
ADK1: 0.0
ADK1_reverse_a6f90: 0.0
AKGDH: 0.0
AKGDH_reverse_08bdc: 0.0
AKGt2r: 0.0
AKGt2r_reverse_5d500: 0.0
ALCD2x: 0.0
ALCD2x_reverse_5d107: 0.0
ATPM: 8.39
ATPM_reverse_5b752: 0.0
ATPS4r: 7.910330512594384
ATPS4r_reverse_64306: 0.0
Biomass_Ecoli_core: 0.08327066253055962
Biomass_Ecoli_core_reverse_2cdba: 0.0
CO2t: 0.0
CO2t_reverse_7c42f: 3.4580751456507546
CS: 0.0898407178042207
CS_reverse_8d7e9: 0.0
CYTBD: 6.72361186539835
CYTBD_reverse_611ba: 0.0
D_LACt2: 0.0
D_LACt2_reverse_d0dc8: 0.0
ENO: 3.410706629270247
ENO_reverse_40eea: 0.0
ETOHt2r: 0.0
ETOHt2r_reverse_b3d52: 0.0
EX_ac_e: 2.491048778150239
EX_ac_e_reverse_0be96: 0.0
EX_acald_e: 0.0
EX_acald_e_reverse_c096e: 0.0
EX_akg_e: 0.0
EX_akg_e_reverse_70d85: 0.0
EX_co2_e: 3.4580751456507546
EX_co2_e_reverse_d0466: 0.0
EX_etoh_e: 0.0
EX_etoh_e_reverse_cc64f: 0.0
EX_for_e: 1.3516910061029545e-15
EX_for_e_reverse_23269: 0.0
EX_fru_e: 0.0
EX_fru_e_reverse_c3828: 0.0
EX_fum_e: 0.0
EX_fum_e_reverse_e3432: 0.0
EX_glc__D_e: 0.0
EX_glc__D_e_reverse_af641: 1.9972995635450779
EX_gln__L_e: 0.0
EX_gln__L_e_reverse_6a1a1: 0.0
EX_glu__L_e: 0.0
EX_glu__L_e_reverse_42f6c: 0.0
EX_h_e: 4.161458268513264
EX_h_e_reverse_3e0c5: 0.0
EX_h2o_e: 4.064651959788374
EX_h2o_e_reverse_3ced4: 0.0
EX_lac__D_e: 0.0
EX_lac__D_e_reverse_f95b4: 0.0
EX_mal__L_e: 0.0
EX_mal__L_e_reverse_af154: 0.0
EX_nh4_e: 0.0
EX_nh4_e_reverse_f9cc6: 0.45405826864663545
EX_o2_e: 0.0
EX_o2_e_reverse_efa94: 3.361805932699174
EX_pi_e: 0.0
EX_pi_e_reverse_1fb09: 0.30632778625118356
EX_pyr_e: 0.0
EX_pyr_e_reverse_1f6de: 0.0
EX_succ_e: 0.0
EX_succ_e_reverse_a9039: 0.0
FBA: 1.6765090510567253
FBA_reverse_84806: 0.0
FBP: 0.0
FBP_reverse_bf2c9: 0.0
FORt2: 0.0
FORt2_reverse_89839: 0.0
FORti: 1.3516910061029545e-15
FORti_reverse_18c06: 0.0
FRD7: 0.0
FRD7_reverse_e0172: 0.0
FRUpts2: 0.0
FRUpts2_reverse_58d3a: 0.0
FUM: 0.0
FUM_reverse_d3642: 0.0
FUMt2_2: 0.0
FUMt2_2_reverse_7b4b6: 0.0
G6PDH2r: 0.7138835534076138
G6PDH2r_reverse_19ddf: 0.0
GAPD: 3.535279540415964
GAPD_reverse_459c1: 0.0
GLCpts: 1.9972995635450779
GLCpts_reverse_a52ae: 0.0
GLNS: 0.02129230840906415
GLNS_reverse_59581: 0.0
GLNabc: 0.0
GLNabc_reverse_1d82a: 0.0
GLUDy: 0.0
GLUDy_reverse_fa4e7: 0.4327659602375713
GLUN: 0.0
GLUN_reverse_4ccdb: 0.0
GLUSy: 0.0
GLUSy_reverse_6a00f: 0.0
GLUt2r: 0.0
GLUt2r_reverse_3e88a: 0.0
GND: 0.7138835534076138
GND_reverse_eec5c: 0.0
H2Ot: 0.0
H2Ot_reverse_aa560: 4.064651959788374
ICDHyr: 0.08984071780422077
ICDHyr_reverse_7f84b: 0.0
ICL: 0.0
ICL_reverse_2f27e: 0.0
LDH_D: -6.75845503051477e-16
LDH_D_reverse_f8507: 0.0
MALS: 0.0
MALS_reverse_d7382: 0.0
MALt2_2: 0.0
MALt2_2_reverse_a635f: 0.0
MDH: 0.0
MDH_reverse_ee52c: 0.0
ME1: 0.0
ME1_reverse_9736c: 0.0
ME2: 0.0
ME2_reverse_2b0a2: 0.0
NADH16: 6.72361186539835
NADH16_reverse_330a2: 0.0
NADTRHD: 0.0
NADTRHD_reverse_49725: 0.0
NH4t: 0.45405826864663545
NH4t_reverse_551ee: 0.0
O2t: 3.361805932699174
O2t_reverse_4d957: 0.0
PDH: 2.892971284986491
PDH_reverse_ca160: 0.0
PFK: 1.6765090510567255
PFK_reverse_d24a6: 0.0
PFL: 0.0
PFL_reverse_af9ec: 0.0
PGI: 1.2663455243186994
PGI_reverse_27efc: 0.0
PGK: 0.0
PGK_reverse_02696: 3.535279540415964
PGL: 0.7138835534076138
PGL_reverse_2bb6b: 0.0
PGM: 0.0
PGM_reverse_fc9af: 3.410706629270247
PIt2r: 0.30632778625118356
PIt2r_reverse_1cd61: 0.0
PPC: 0.23862041054757158
PPC_reverse_e854a: 0.0
PPCK: 0.0
PPCK_reverse_2557d: 0.0
PPS: 0.0
PPS_reverse_1c319: 0.0
PTAr: 2.491048778150239
PTAr_reverse_fce15: 0.0
PYK: 1.1315608542579836
PYK_reverse_bc8ff: 0.0
PYRt2: 0.0
PYRt2_reverse_a6e24: 0.0
RPE: 0.4160674167114429
RPE_reverse_a1b04: 0.0
RPI: 0.0
RPI_reverse_853a1: 0.29781613669617085
SUCCt2_2: 0.0
SUCCt2_2_reverse_206ca: 0.0
SUCCt3: 0.0
SUCCt3_reverse_7d82a: 0.0
SUCDi: 0.0
SUCDi_reverse_480f4: 0.0
SUCOAS: 0.0
SUCOAS_reverse_22958: 0.0
TALA: 0.22306406294248743
TALA_reverse_adfda: 0.0
THD2: 0.0
THD2_reverse_f65dd: 0.0
TKT1: 0.22306406294248743
TKT1_reverse_a1021: 0.0
TKT2: 0.19300335376895542
TKT2_reverse_7ebc7: 0.0
TPI: 1.6765090510567253
TPI_reverse_c2c3b: 0.0

In [1]:
from cobra.io import load_model, load_json_model, load_matlab_model, read_sbml_model
from cobra.util.solver import linear_reaction_coefficients
import cobra
import pandas as pd

In [3]:

# setting the solver
cobra_config = cobra.Configuration()
cobra_config.solver = 'gurobi'
growthRate = 0.1

In [4]:
## required inputs to the model

# setting the solver
cobra_config = cobra.Configuration()
# cobra_config.solver = 'gur'
growthRate = 0.1
modelNames = ['Lachnospiraceae_species','Bacteroides_ovatus','Bifidobacterium_longum',
'Collinsella_aerofaciens','Escherichia_coli','Klebsiella_aerogenes','Muricomes_intestini','Parabacteroides_distasonis']
modelPaths = ['../../Data/HDC/HDC1_gapseq/180_genome.xml',
'../../Data/HDC/HDC1_gapseq/376_genome.xml',
'../../Data/HDC/HDC1_gapseq/370_genome.xml',
'../../Data/HDC/HDC1_gapseq/374_genome.xml',
'../../Data/HDC/HDC1_gapseq/382_genome.xml',
'../../Data/HDC/HDC1_gapseq/bin1.xml',
'../../Data/HDC/HDC1_gapseq/380_genome.xml',
'../../Data/HDC/HDC1_gapseq/378_genome.xml']
modelWeights = [0.000001,0.008976,0.000124,0.000007,0.000085,0.000121,0.000082,0.000426]

modelDetails = pd.DataFrame({'Name':modelNames,'Path':modelPaths,'weight':modelWeights})
modelDetails.head()

,Name,Path,weight
0,Lachnospiraceae_species,../../Data/HDC/HDC1_gapseq/180_genome.xml,0.000001
1,Bacteroides_ovatus,../../Data/HDC/HDC1_gapseq/376_genome.xml,0.008976
2,Bifidobacterium_longum,../../Data/HDC/HDC1_gapseq/370_genome.xml,0.000124
3,Collinsella_aerofaciens,../../Data/HDC/HDC1_gapseq/374_genome.xml,0.000007
4,Escherichia_coli,../../Data/HDC/HDC1_gapseq/382_genome.xml,0.000085

In [8]:
# exchange reactions (from metabolomics data)
exchangeRate = pd.read_excel('../../Data/HDC/HDC1_metabolomicsdata_preliminary_formodelling.xlsx')
exchangeRate['Consumed'] = exchangeRate['Conc. in GF mouse 23A (mmol per g dry weight)']-exchangeRate['Conc. in HDC1 mouse 29A (mmol per g dry weight)']
exchangeRate.head()

,metabolite name,metabolite ID,present in gapseq models?,Conc. in GF mouse 23A (mmol per g dry weight),Conc. in HDC1 mouse 29A (mmol per g dry weight),consumed or produced?,Consumed
0,Adenosine,cpd00182,Y,0.000048,0.000011,consumed,0.000037
1,Cytidine,cpd00367,Y,0.000803,0.000066,consumed,0.000738
2,Deoxyguanosine,cpd00277,Y,0.000482,0.000104,consumed,0.000378
3,Guanosine,cpd00311,Y,0.001281,0.000044,consumed,0.001237
4,Inosine,cpd00246,Y,0.001039,0.000151,consumed,0.000888

In [9]:
def load_and_process_models(path2models, modelNames):
    models = []
    biomass_reactions = []
    for path in path2models:
        if path.endswith('.mat'):
            model = load_matlab_model(path)
        elif path.endswith('.json'):
            model = load_json_model(path)
        elif path.endswith('.xml'):
            model = read_sbml_model(path)

        # Rename reactions
        for reaction in model.reactions:
            reaction.id = f"{modelNames[path2models.index(path)]}_{reaction.id}"

        # Rename metabolites
        for metabolite in model.metabolites:
            metabolite.id = f"{modelNames[path2models.index(path)]}_{metabolite.id}"

        # Repair the model to update internal indexes
        model.repair()
        biomass_reactions.append([reaction for reaction in model.reactions if reaction.objective_coefficient != 0][0].id)
        models.append(model)
    return models, biomass_reactions

In [10]:
def merge_models(models):
    merged_model = models[0].copy()
    for model in models[1:]:
        merged_model.merge(model)
    return merged_model

In [11]:
def add_biomass_weight_and_update_constraints(merged_model, modelNames):
    # defining the variables for the biomass weights
    name2expression = {m:merged_model.problem.Variable(m+'_biomass_weight', lb=0, ub=1000, type="continuous") for m in modelNames}
    merged_model.add_cons_vars(name2expression.values())
    merged_model.solver.update()
    # setting the bounds for the reactions based on the biomass weights and default bounds
    constraints = []
    for reaction in merged_model.reactions:
        bio_id = [i for i,j in enumerate(modelNames) if j in reaction.id][0] # getting the index of the model name 
        constraint_ub = merged_model.problem.Constraint(reaction.flux_expression-(reaction.upper_bound*name2expression[modelNames[bio_id]]), ub=0, name=f"{reaction.id}_bio_weight_ub")
        constraint_lb = merged_model.problem.Constraint(reaction.flux_expression-(reaction.lower_bound*name2expression[modelNames[bio_id]]), lb=0, name=f"{reaction.id}_bio_weight_lb")
        constraints.append(constraint_ub)
        constraints.append(constraint_lb)
    merged_model.add_cons_vars(constraints)
    merged_model.solver.update()
    return merged_model

In [12]:
def add_biomass_flux_constraints(growthRate, merged_model, biomass_reactions, modelNames):
    # setting the biomass flux constraints
    biomass_constraints = []
    for reaction in biomass_reactions:
        modelName = modelNames[[i for i,j in enumerate(modelNames) if j in reaction][0]]
        biomass_wt = modelName+'_biomass_weight'
        constraint = merged_model.problem.Constraint(merged_model.reactions.get_by_id(reaction).flux_expression-growthRate*merged_model.variables[biomass_wt], lb=0, ub=0,name=f"{modelName}_flux_bio_weight")
        biomass_constraints.append(constraint)
    merged_model.add_cons_vars(biomass_constraints)
    merged_model.solver.update()
    return merged_model

In [13]:
def add_total_biomass_constraint(X0, merged_model, modelNames):
    constraint = merged_model.problem.Constraint(sum([merged_model.variables[modelName+'_biomass_weight'] for modelName in modelNames])-X0, lb=0, ub=0, name='total_biomass_weight')
    merged_model.add_cons_vars(constraint)
    merged_model.solver.update()
    return merged_model

In [14]:
def get_exchange_rxn_met_mapping(model):
    exchange_reactions = [i.id for i in model.exchanges] # all the exchange reactions in the model
    exchange_mets = [list(i.metabolites.keys())[0].id for i in model.exchanges] # all the exchange metabolites in the model
    return pd.DataFrame({'Exchange_rxns':exchange_reactions, 'Exchange_mets':exchange_mets})

In [33]:
def add_metabolomics_constraints(merged_model, exchangeRate, met2rxn):
    metabolomics_constraints = []
    for met in list(exchangeRate['metabolite ID']):
        exc_rxns = list(met2rxn[met2rxn.Exchange_mets.apply(lambda x: met in x)]['Exchange_rxns'])
        consumption_rate = exchangeRate[exchangeRate['metabolite ID']==met]['Consumed'].values[0]
        constraint = merged_model.problem.Constraint(sum([merged_model.reactions.get_by_id(r).flux_expression for r in exc_rxns])+consumption_rate, lb=0, ub=0,name=f"{met}_metabolomics_constraint")
        metabolomics_constraints.append(constraint)
    merged_model.add_cons_vars(metabolomics_constraints)
    merged_model.solver.update()
    return merged_model

In [42]:
def add_absolute_values_constraints(merged_model, modelNames, exp_weights):
    constraints = []
    for i,weight in enumerate(exp_weights):
        z_variable = merged_model.problem.Variable(f"z_{modelNames[i]}", lb=0, ub=1000, type="continuous")
        constraint_lb = merged_model.problem.Constraint(merged_model.variables[modelNames[i]+'_biomass_weight']-weight+z_variable, lb=0, name=f"{modelNames[i]}_exp_weight_lb")
        constraint_ub = merged_model.problem.Constraint(merged_model.variables[modelNames[i]+'_biomass_weight']-weight-z_variable, ub=0, name=f"{modelNames[i]}_exp_weight_ub")
        constraints.append(constraint_lb)
        constraints.append(constraint_ub)
    merged_model.add_cons_vars(constraints)
    merged_model.solver.update()
    return merged_model

In [48]:
def set_model_objective(merged_model, modelNames):
    objective = merged_model.problem.Objective(sum([merged_model.variables['z_'+modelName] for modelName in modelNames]), direction='min')
    merged_model.objective = objective
    return merged_model

In [50]:
# modelPaths = list(modelDetails.Path)
# modelNames = list(modelDetails.Name)
# exp_weights = list(modelDetails.weight)
# ## running the simulation
# models, biomass_reactions =load_and_process_models(modelPaths, modelNames)
# merged_model = merge_models(models)
# merged_model = add_biomass_weight_and_update_constraints(merged_model, modelNames)
# merged_model = add_biomass_flux_constraints(growthRate, merged_model, biomass_reactions, modelNames)
# X0 = sum(list(modelDetails.weight))
# merged_model = add_total_biomass_constraint(X0, merged_model, modelNames)
# met2rxn = get_exchange_rxn_met_mapping(merged_model)
# merged_model = add_metabolomics_constraints(merged_model, exchangeRate, met2rxn)
# merged_model = add_absolute_values_constraints(merged_model, modelNames, exp_weights)
merged_model = set_model_objective(merged_model, modelNames)
solution = merged_model.optimize(objective_sense=None)

c:\Users\Admin\anaconda3\envs\carveme\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)